### ISSUE TITLE
j.tools.sandboxer.sandbox_build() is not working 

### ISSUE THREAD

**Issue by andrewayoub** [threefoldtecharchive/jumpscaleX_archived#109]
j.tools.sandboxer.sandbox_build() is not working

**Comment by Dina-Abd-Elrahman** [comment]
- i got this error 

```
Mon28 10:51  InstallTools.py   - 664: DEBUG      execute:source /sandbox/env.sh;/sandbox/var/build/python3/bin/python3 -c 'import ssl'
OK
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/sandbox/var/build/python3/lib/python3.6/ssl.py", line 101, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'
Mon28 10:51  InstallTools.py   - 776: DEBUG      system.process.run ended, exitcode was 1
Mon28 10:51  InstallTools.py   - 778: DEBUG      system.process.run stdout:
OK

Mon28 10:51  InstallTools.py   - 780: DEBUG      system.process.run stderr:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/sandbox/var/build/python3/lib/python3.6/ssl.py", line 101, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/sandbox/bin/js_shell in <module>()
----> 1 j.tools.sandboxer.sandbox_build()

/sandbox/lib/jumpscale/Jumpscale/tools/sandboxer/Sandboxer.py in sandbox_build(self, reset)
     28         :return:
     29         """
---> 30         j.builder.runtimes.python.build(reset=reset)
     31         j.builder.runtimes.python._copy2sandbox_github()
     32         j.builder.runtimes.lua.build()  # will build openresty & lua & openssl

/sandbox/lib/jumpscale/Jumpscale/builder/runtimes/BuilderPython.py in build(self, reset, sandbox, tag)
    115             rc, out, err = j.sal.process.execute(cmd, die=False)
    116             if rc > 0:
--> 117                 raise RuntimeError("SSL was not included well\n%s" % err)
    118             self._done_set("compile")
    119 

RuntimeError: SSL was not included well
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/sandbox/var/build/python3/lib/python3.6/ssl.py", line 101, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'

```

**Comment by despiegk** [comment]
check https://github.com/threefoldtech/jumpscaleX/issues/155

**Comment by Dina-Abd-Elrahman** [comment]
- it's outdated , we can close it.
