### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtecharchive/jumpscaleX_archived#179]
cloned the repo first
`sudo python3 /sandbox/code/github/threefoldtech/jumpscaleX/install/install.py`
answered 'y' on all questions that gave options to install optional components
```
Wed20 07:50 DocSite.py       - 236 - docsite:docsite                    : found
        file:/sandbox/code/github/threefoldfoundation/info_grid/docs/tf_farming/images/branch_select.png
    ERROR: duplication file in
        docsite:/sandbox/code/github/threefoldfoundation/info_grid/docs,/sandbox/code/github/threefoldfoundation/info_grid/docs/tf_farming/images/branch_select.png

stderr:
    Traceback (most recent call last):
      File "/sandbox/bin/js_shell", line 25, in <module>
        exec(toexec)
      File "<string>", line 1, in <module>
      File "/sandbox/lib/jumpscale/Jumpscale/tools/markdowndocs/MarkDownDocs.py", line 365, in test
        ds6.write()
      File "/sandbox/lib/jumpscale/Jumpscale/tools/markdowndocs/DocSite.py", line 534, in write
        self.load()
      File "/sandbox/lib/jumpscale/Jumpscale/tools/markdowndocs/DocSite.py", line 227, in load
        callbackForMatchFile=callbackForMatchFile)
      File "/sandbox/lib/jumpscale/Jumpscale/sal/fs/SystemFSWalker.py", line 215, in walkFunctional
        callbackForMatchFile, findDirectorySymlinks=findDirectorySymlinks)
      File "/sandbox/lib/jumpscale/Jumpscale/sal/fs/SystemFSWalker.py", line 254, in _walkFunctional
        findDirectorySymlinks=findDirectorySymlinks)
      File "/sandbox/lib/jumpscale/Jumpscale/sal/fs/SystemFSWalker.py", line 254, in _walkFunctional
        findDirectorySymlinks=findDirectorySymlinks)
      File "/sandbox/lib/jumpscale/Jumpscale/sal/fs/SystemFSWalker.py", line 227, in _walkFunctional
        callbackFunctionFile(path2, arg)
      File "/sandbox/lib/jumpscale/Jumpscale/tools/markdowndocs/DocSite.py", line 208, in callbackFunctionFile
        self.file_add(path)
      File "/sandbox/lib/jumpscale/Jumpscale/tools/markdowndocs/DocSite.py", line 239, in file_add
        raise j.exceptions.Input(message="duplication file in
        %s,%s" %  (self, path))
```

**Comment by robvanmieghem** [comment]
this also prevents the rest of kosmos to work properly:
```
tc= j.clients.tfchain.testnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/jumpscale_generated.py", line 563, in tfchain
    from Jumpscale.clients.blockchain.tfchain.TFChainClientFactory import TFChainClientFactory
  File "/sandbox/lib/jumpscale/Jumpscale/clients/blockchain/tfchain/TFChainClientFactory.py", line 10, in <module>
    from .types.Errors import ErrorTypes
ModuleNotFoundError: No module named 'Jumpscale.clients.blockchain.tfchain.types.Errors'
```

**Comment by rkhamis** [comment]
An error during docsite generation shouldn't break the installation.

Instead, let's create a report with all the errors encountered and show it at the end of the installation where there are errors

**Comment by Dinaamagdy** [comment]
verified on jsx development branch
