### ISSUE TITLE
error while installing js with lua and openresty

### ISSUE THREAD

**Issue by 0xIslamTaha** [threefoldtecharchive/jumpscaleX_archived#235]
installing js from development in ubuntu 18 container

```
stderr:
    Traceback (most recent call last):
      File "/sandbox/bin/js_shell", line 25, in <module>
        exec(toexec)
      File "<string>", line 1, in <module>
      File "/sandbox/lib/jumpscale/Jumpscale/builder/runtimes/BuilderLua.py", line 202, in install
        self.build(reset=reset)
      File "/sandbox/lib/jumpscale/Jumpscale/builder/runtimes/BuilderLua.py", line 58, in build
        self.lua_rocks_install(reset)
      File "/sandbox/lib/jumpscale/Jumpscale/builder/runtimes/BuilderLua.py", line 143, in lua_rocks_install
        self.lua_rock_install(line, reset)
      File "/sandbox/lib/jumpscale/Jumpscale/builder/runtimes/BuilderLua.py", line 68, in lua_rock_install
        j.sal.process.execute(j.core.tools.text_replace(C))
      File "/sandbox/lib/jumpscale/Jumpscale/sal/process/SystemProcess.py", line 87, in execute
        env=env,interactive=interactive,replace=replace)
      File "/sandbox/lib/jumpscale/Jumpscale/core/InstallTools.py", line 1010, in execute
        raise RuntimeError(msg)
    RuntimeError:
    Could not execute:    luarocks install lua-term OPENSSL_DIR=/sandbox/var/build/openssl CRYPTO_DIR=/sandbox/var/build/openssl
    
    stdout:
        Installing https://luarocks.org/lua-term-0.7-1.rockspec
    
    stderr:
        Warning: The directory '/root/.cache/luarocks' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner
        of
            that directory. If executing /sandbox/var/build/luarocks/src/bin/luarocks with sudo, you may want sudo's -H flag.
    
        Error: Error fetching file: Failed downloading https://github.com/hoelzro/lua-term/archive/0.07.tar.gz - 0.07.tar.gz

```

**Comment by BolaNasr** [comment]
**i tried it in new  docker :** 
``` curl https://raw.githubusercontent.com/threefoldtech/jumpscaleX/development/install/install.py?$RANDOM > /tmp/install.py;python3 /tmp/install.py 1 y y y y y```
**it works good**
i think it's network issue
