### ISSUE TITLE
tfchain client wallet creation fails

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtecharchive/jumpscaleX_archived#277]
Branch: **Development**

Reproduce: 

`c = j.clients.tfchain.new('my_client', network_type='TEST')`
`w = c.wallets.new("my_wallet")`

Gives following error:

```
JSX> w = c.wallets.new("my_wallet")  # a new seed will be generated
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBaseConfigs.py", line 59, in new
    self._children[name] = kl(parent=self, data=data, **kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBaseConfig.py", line 19, in __init__
    JSBaseDataObj.__init__(self,data=data, parent=parent, topclass=False,**kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBaseDataObj.py", line 36, in __init__
    if kwargs=={} and data==None:
  File "/sandbox/lib/jumpscale/Jumpscale/data/schema/DataObjBase.py", line 206, in __eq__
    return self._data == val._data
  File "/sandbox/lib/jumpscale/Jumpscale/data/schema/DataObjBase.py", line 159, in _data
    self._cobj_=self._cobj.as_builder()
  File "/sandbox/var/codegen/schema_jumpscale_tfchain_wallet.py", line 243, in _cobj
    raise RuntimeError(msg)
RuntimeError:
ERROR: could not create capnp message
    {
     "keyCount": 1,
     "keyScanCount": -1,
     "name": "my_wallet"
    }


schema:
    <capnp.lib.capnp._StructModule object at 0x110230ac8>


error was:
capnp/dynamic.c++:1675: failed: expected value >= 0 && T(value) == value; Value out-of-range for requested type.; value = -1
stack: 0x10e0c3980 0x10e0c7f63 0x10df7ab4f 0x10df3bb76 0x10df82b2a 0x10dfdad57 0x10dfca877 0x10dfca3ef 0x10bb0e09f 0x10bb0f3f1 0x10bb0e7a1 0x10bb9d2bc 0x10bb0ea6e 0x10bb14b97 0x10bb3b6b3 0x10bba15bb 0x10bb0ea6e 0x10bb14b97 0x10bb3b6b3 0x10bba15bb 0x10bb0ea6e 0x10bb0f304 0x10bb4c753 0x10bb3adb4 0x10bba169b 0x10bba4c6b 0x10bb0e2c1 0x10bb9d2bc 0x10bba4c6b 0x10bb0e2c1 0x10bb0f3f1

```

**Comment by DylanVerstraete** [comment]
deprecated, works right now
