### ISSUE TITLE
Error when reserving a vm on a farm

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtecharchive/jumpscaleX_archived#321]
JSX Branch **development**

Following documentation https://github.com/threefoldfoundation/info_grid/tree/development/docs/capacity_reservation

Error when reserving a zos vm:

```python
JSX> result = w.capacity.reserve_zos_vm(
   2     email='dylan@threefold.tech', # the email on which you will received the connection information
   3     threebot_id='my3bot.dylan', # your threebot id, it can be any of the names you gave to your 3bot
   4     location='0025902dbb36', # name of the farm or node id where to deploy the workload
   5     size=1)

Tue 09 13:42:38 GedisClient.py   - 133 - j.clients.gedis:gedisclient        : redisclient: notary.grid.tf:5000
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/clients/blockchain/tfchain/TFChainCapacity.py", line 133, in reserve_zos_vm
    return self._process_reservation(reservation, threebot_id, source=source, refund=refund)
  File "/sandbox/lib/jumpscale/Jumpscale/clients/blockchain/tfchain/TFChainCapacity.py", line 235, in _process_reservation
    refund=refund)
  File "/sandbox/lib/jumpscale/Jumpscale/clients/blockchain/tfchain/TFChainWallet.py", line 345, in coins_send
    amount = Currency(value=amount)
  File "/sandbox/lib/jumpscale/Jumpscale/clients/blockchain/tfchain/types/PrimitiveTypes.py", line 170, in __init__
    self.value = value
  File "/sandbox/lib/jumpscale/Jumpscale/clients/blockchain/tfchain/types/PrimitiveTypes.py", line 208, in value
    raise TypeError("cannot set value of type {} as Currency (invalid type)".format(type(value)))
TypeError: cannot set value of type <class 'float'> as Currency (invalid type)

cannot set value of type <class 'float'> as Currency (invalid type)
```

**Comment by zaibon** [comment]
https://github.com/threefoldtech/jumpscaleX/commit/f98da6647fb4cad60a6dd924a0a0e908a20ac39f
