### ISSUE TITLE
errors installing jsx (docker) on Mac

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtecharchive/jumpscaleX_archived#324]
JSX Branch **development**

Following errors are thrown when installing jsx in a docker on mac. The installation succeeds afterwards

```python
Error processing line 1 of /Users/dylan/Library/Python/3.7/lib/python/site-packages/zerohub-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 580, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
Error processing line 1 of /usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zerohub-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 580, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
```

**Comment by waleedhammam** [comment]
can you add steps lead to this case ?
is it a fresh installation, or there was already code on the machine

**Comment by DylanVerstraete** [comment]
Fresh installation, no code on my machine

**Comment by waleedhammam** [comment]
Is the installation with `sudo` ?

**Comment by DylanVerstraete** [comment]
no

**Comment by waleedhammam** [comment]
can you pull and try again ?
also if you may add your installation steps you used.

**Comment by DylanVerstraete** [comment]
I pulled and tried again, had the same result. JSX installed did succeed afterwards.

**Comment by DylanVerstraete** [comment]
Errors occurs only with my Python version. Which might be corrupt.
