### ISSUE TITLE
3bot name not found when reserving capacity

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtecharchive/jumpscaleX_archived#328]
JSX branch **development**

When reserving capacity with 3bot as following:

```python
JSX> result = w.threebot.record_new(
   2     months=1, # default is 1, can be omitted to keep it at default,
   3               # or can be anything of inclusive range of [1,24]
   4     names=["botdylan.something"], # names can be omitted as well, as long as you have 1 address
   5     addresses=["example.org"], # addresses can be omitted as well, as long as you have 1 name
   6     key_index=0) # optionally leave key_index at default value of None


JSX> result = w.capacity.reserve_zos_vm(
   2     email='verstrad@threefold.tech', # the email on which you will received the connection information
   3     threebot_id='botdylan.something', # your threebot id, it can be any of the names you gave to your 3bot
   4     location='d8cb8ac6e11d', # name of the farm or node id where to deploy the workload
   5     size=1)
```

I get the following stacktrace:
```python
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/clients/blockchain/tfchain/TFChainCapacity.py", line 134, in reserve_zos_vm
    return self._process_reservation(reservation, threebot_id, source=source, refund=refund)
  File "/sandbox/lib/jumpscale/Jumpscale/clients/blockchain/tfchain/TFChainCapacity.py", line 217, in _process_reservation
    self._wallet.client.threebot.record_get(threebot_id)
  File "/sandbox/lib/jumpscale/Jumpscale/clients/blockchain/tfchain/TFChainClient.py", line 728, in record_get
    resp = self._client.explorer_get(endpoint=endpoint)
  File "/sandbox/lib/jumpscale/Jumpscale/clients/blockchain/tfchain/TFChainClient.py", line 389, in _explorer_get
    return j.clients.tfchain.explorer.get(addresses=self.explorer_addresses, endpoint=endpoint)
  File "/sandbox/lib/jumpscale/Jumpscale/clients/blockchain/tfchain/TFChainExplorerClient.py", line 50, in get
    raise j.clients.tfchain.errors.ExplorerServerError("GET: error (code: {}): {}".format(e.status_code, e.msg), endpoint)
Jumpscale.clients.blockchain.tfchain.types.Errors.ExplorerServerError: /explorer/whois/3bot/botdylan.something: GET: error (code: 500): b'{"message":"3bot name not found"}\n'

/explorer/whois/3bot/botdylan.something: GET: error (code: 500): b'{"message":"3bot name not found"}\n'
```

**Comment by zaibon** [comment]
yeah as documented in the tfchain client: https://github.com/threefoldtech/jumpscaleX/tree/master/Jumpscale/clients/blockchain/tfchain#create-and-manage-3bot-records
You need to wait a bit for the 3bot record to be included in a block. So creating it and then directly doing a reservation won't work.
Retry now you 3bot record seems to be processed now: https://explorer2.testnet.threefoldtoken.com/3bot.html?name=botdylan.something

**Comment by DylanVerstraete** [comment]
Works, thanks
