### ISSUE TITLE
when reserving capacity connection to notary.grid.tf is refused

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtecharchive/jumpscaleX_archived#330]
JSX branch **development**

when executing following:
```python
JSX> result = w.capacity.reserve_zos_vm(
   2     email='verstrad@threefold.tech', # the email on which you will received the connection information
   3     threebot_id='botdylan.something', # your threebot id, it can be any of the names you gave to your 3bot
   4     location='d8cb8ac6e11d', # name of the farm or node id where to deploy the workload
   5     size=1)
````

I get following stacktrace:
```python
Wed 10 10:36:05 GedisClient.py   - 133 - j.clients.gedis:gedisclient        : redisclient: notary.grid.tf:5000
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/clients/blockchain/tfchain/TFChainCapacity.py", line 134, in reserve_zos_vm
    return self._process_reservation(reservation, threebot_id, source=source, refund=refund)
  File "/sandbox/lib/jumpscale/Jumpscale/clients/blockchain/tfchain/TFChainCapacity.py", line 231, in _process_reservation
    response = self._notary_client.register(threebot_id, signature.message, signature.signature)
  File "/sandbox/lib/jumpscale/Jumpscale/clients/blockchain/tfchain/TFChainCapacity.py", line 27, in _notary_client
    self._notary_client_ = c.actors.notary_actor
  File "/sandbox/lib/jumpscale/DigitalMe/clients/gedis/GedisClient.py", line 70, in actors
    assert self.ping()
  File "/sandbox/lib/jumpscale/DigitalMe/clients/gedis/GedisClient.py", line 51, in ping
    test = self._redis.execute_command("ping")
  File "/root/.local/lib/python3.6/site-packages/redis/client.py", line 772, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/root/.local/lib/python3.6/site-packages/redis/connection.py", line 994, in get_connection
    connection.connect()
  File "/root/.local/lib/python3.6/site-packages/redis/connection.py", line 497, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to notary.grid.tf:5000. Connection refused.

Error 111 connecting to notary.grid.tf:5000. Connection refused.
```

**Comment by DylanVerstraete** [comment]
It works again
