### ISSUE TITLE
cannot use build in capnp builder

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtecharchive/jumpscaleX_archived#333]
an eror while trying to use capnp builder 

![error](https://user-images.githubusercontent.com/21218053/55879841-d0a65480-5b9f-11e9-99e4-585dfb76081b.png)

**Comment by AhmedHanafy725** [comment]
After this commit 3b25db711a0aa01d9a9514882d58bbe920b33b30

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/builder/system/BuilderBaseClass.py", line 67, in wrapper_action
    res = func(builder, *args, **kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/builder/libs/BuilderCapnp.py", line 38, in build
    self._execute(script)
  File "/sandbox/lib/jumpscale/Jumpscale/builder/system/BuilderBaseClass.py", line 277, in _execute
    args=args, interactive=interactive, replace=False, showout=showout)
  File "/sandbox/lib/jumpscale/Jumpscale/sal/process/SystemProcess.py", line 87, in execute
    env=env,interactive=interactive,replace=replace)
  File "/sandbox/lib/jumpscale/Jumpscale/core/InstallTools.py", line 1161, in execute
    raise RuntimeError(msg)
RuntimeError: 
Could not execute:    bash /tmp/builders/capnp/builder_capnp.sh

stderr:
    + cd /tmp/builders/capnp
    + . /tmp/builders/capnp/env.sh
    ++ export LIBRARY_PATH=/lib/x86_64-linux-gnu:/lib:/usr/local/lib:/usr/lib
    ++ LIBRARY_PATH=/lib/x86_64-linux-gnu:/lib:/usr/local/lib:/usr/lib
    ++ export LD_LIBRARY_PATH=/lib/x86_64-linux-gnu:/lib:/usr/local/lib:/usr/lib
    ++ LD_LIBRARY_PATH=/lib/x86_64-linux-gnu:/lib:/usr/local/lib:/usr/lib
    ++ export 'LDFLAGS=-L/lib/x86_64-linux-gnu -L/lib -L/usr/local/lib -L/usr/lib'
    ++ LDFLAGS='-L/lib/x86_64-linux-gnu -L/lib -L/usr/local/lib -L/usr/lib'
    ++ export CPPPATH=/usr/include
    ++ CPPPATH=/usr/include
    ++ export CPPFLAGS=-I/usr/include
    ++ CPPFLAGS=-I/usr/include
    ++ export PS1=PYTHONBUILDENV:
    ++ PS1=PYTHONBUILDENV:
    ++ export PYTHONHTTPSVERIFY=0
    ++ PYTHONHTTPSVERIFY=0
    ++ export LC_ALL=en_US.UTF-8
    ++ LC_ALL=en_US.UTF-8
    ++ export LANG=en_US.UTF-8
    ++ LANG=en_US.UTF-8
    + cd /tmp/builders/capnp
    + ./configure CXXFLAGS=-DHOLES_NOT_SUPPORTED
    /tmp/builders/capnp/builder_capnp.sh: line 5: ./configure: No such file or directory
```

**Comment by Dina-Abd-Elrahman** [comment]
- capnp builder are working good now.
