### ISSUE TITLE
Bad value for --with-lua: /sandbox/openresty/luajit is not a valid directory

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/jumpscaleX_archived#338]
Fresh installation with openresty/lua/wikis option using docs command

```
curl https://raw.githubusercontent.com/threefoldtech/jumpscaleX/development/install/install.py?$RANDOM > /tmp/install.py;python3 /tmp/install.py
```

```
Error in sys.excepthook:
Traceback (most recent call last):
  File "/tmp/InstallTools.py", line 58, in my_excepthook
    Tools.log(msg=exception_obj,tb=tb,level=40)
  File "/tmp/InstallTools.py", line 416, in log
    Tools.log2stdout(logdict,data_show=data_show)
  File "/tmp/InstallTools.py", line 884, in log2stdout
    msg=Tools.text_replace(msg,args=logdict)
  File "/tmp/InstallTools.py", line 812, in text_replace
    content = content.format_map(replace_args)
ValueError: Format string contains positional fields

Original exception was:
Traceback (most recent call last):
  File "/tmp/install.py", line 381, in <module>
    IT.Tools.execute("source /sandbox/env.sh;kosmos 'j.builder.runtimes.lua.install(reset=True)'", showout=False)
  File "/tmp/InstallTools.py", line 1161, in execute
    raise RuntimeError(msg)
RuntimeError: 
Could not execute:    source /sandbox/env.sh
    kosmos 'j.builder.runtimes.lua.install(reset=True)'

stdout:
    OK
    Mon 15 09:30:09 uilderBaseClass.py - 185 - builderlua:builderlua              : build profile path in:/tmp/builders/lua/env.sh
    Mon 15 09:30:09 uilderBaseClass.py - 185 - systempackage:buildersystempackage : build profile path in:/tmp/builders/SystemPackage/env.sh
    Mon 15 09:30:09 uilderBaseClass.py - 185 - builderopenresty:builderopenresty  : build profile path in:/tmp/builders/openresty/env.sh
    Mon 15 09:30:09 uilderBaseClass.py - 185 - builderopenssl:builderopenssl      : build profile path in:/tmp/builders/openssl/env.sh
    Mon 15 09:30:09 BuilderTools.py  - 176 - j.builder.tools:buildertools       : curl -L 'https://luarocks.org/releases/luarocks-3.0.4.tar.gz' -o
        '/tmp/jumpscale/luarocks-3.0.4.tar.gz'   --connect-timeout 30 --retry 3 --retry-max-time 0
    Mon 15 09:30:09 BuilderTools.py  - 692 - j.builder.tools:buildertools       : curl -L 'https://luarocks.org/releases/luarocks-3.0.4.tar.gz' -o
        '/tmp/jumpscale/luarocks-3.0.4.tar.gz'   --connect-timeout 30 --retry 3 --retry-max-time 0
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
       0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 100   167  100   167
        0     0     91      0  0:00:01  0:00:01 --:--:--    91 100   167  100   167    0     0     91      0  0:00:01  0:00:01 --:--:--    91
       0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0 100  200k  100  200k    0     0  59349      0  0:00:03  0:00:03 --:--:--  251k
    Mon 15 09:30:13 BuilderTools.py  - 202 - j.builder.tools:buildertools       : file_expand:/tmp/jumpscale/luarocks-3.0.4.tar.gz
    Mon 15 09:30:13 BuilderTools.py  - 692 - j.builder.tools:buildertools       : tar -C /tmp/builders/lua/luarocks -xzf /tmp/jumpscale/luarocks-3.0.4.tar.gz
    Mon 15 09:30:13 BuilderTools.py  - 692 - j.builder.tools:buildertools       : cd /tmp/builders/lua/luarocks;find . -maxdepth 1 -type d
    
    
    EXCEPTION
    
            /sandbox/bin/kosmos                                          : 145 : exec(toexec,globals(),j._locals_get({}))
            <string>                                                     : 1   :
            x/lib/jumpscale/Jumpscale/builder/system/BuilderBaseClass.py : 47  : builder.build()
            x/lib/jumpscale/Jumpscale/builder/system/BuilderBaseClass.py : 67  : res = func(builder, *args, **kwargs)
            ndbox/lib/jumpscale/Jumpscale/builder/runtimes/BuilderLua.py : 39  : self._execute(C, showout=False)
            x/lib/jumpscale/Jumpscale/builder/system/BuilderBaseClass.py : 277 : args=args, interactive=interactive, replace=False, showout=showout)
            sandbox/lib/jumpscale/Jumpscale/sal/process/SystemProcess.py : 87  : env=env,interactive=interactive,replace=replace)
            /sandbox/lib/jumpscale/Jumpscale/core/InstallTools.py        : 1161: raise RuntimeError(msg)
    
    Mon 15 09:30:13 <string>         -   1 - <module>                           : EXCEPTION: 
    Could not execute: 'bash /tmp/builders/lua/builder_lua.sh'stdout:
        Bad value for --with-lua: /sandbox/openresty/luajit is not a valid directory.
    
        configure failed.
    
    stderr:
        + cd /tmp/builders/lua
        + . /tmp/builders/lua/env.sh
        ++ export LIBRARY_PATH=/lib/x86_64-linux-gnu:/lib:/usr/local/lib:/usr/lib
        ++ LIBRARY_PATH=/lib/x86_64-linux-gnu:/lib:/usr/local/lib:/usr/lib
        ++ export LD_LIBRARY_PATH=/lib/x86_64-linux-gnu:/lib:/usr/local/lib:/usr/lib
        ++ LD_LIBRARY_PATH=/lib/x86_64-linux-gnu:/lib:/usr/local/lib:/usr/lib
        ++ export 'LDFLAGS=-L/lib/x86_64-linux-gnu -L/lib -L/usr/local/lib -L/usr/lib'
        ++ LDFLAGS='-L/lib/x86_64-linux-gnu -L/lib -L/usr/local/lib -L/usr/lib'
        ++ export CPPPATH=/usr/include
        ++ CPPPATH=/usr/include
        ++ export CPPFLAGS=-I/usr/include
        ++ CPPFLAGS=-I/usr/include
        ++ export PS1=PYTHONBUILDENV:
        ++ PS1=PYTHONBUILDENV:
        ++ export PYTHONHTTPSVERIFY=0
        ++ PYTHONHTTPSVERIFY=0
        ++ export LC_ALL=en_US.UTF-8
        ++ LC_ALL=en_US.UTF-8
        ++ export LANG=en_US.UTF-8
        ++ LANG=en_US.UTF-8
        + cd /tmp/builders/lua/luarocks
        + ./configure --prefix=/sandbox/openresty/luarocks --with-lua=/sandbox/openresty/luajit
    
    
    CANNOT CONTINUE

```

**Comment by waleedhammam** [comment]
it's because of https://github.com/threefoldtech/jumpscaleX/issues/342 , will check after lua builder fix

**Comment by waleedhammam** [comment]
you can pull and try again now

**Comment by xmonader** [comment]
fixed now thanks
