### ISSUE TITLE
lua builder raises an error

### ISSUE THREAD

**Issue by 0xIslamTaha** [threefoldtecharchive/jumpscaleX_archived#342]
```
JSX> j.builder.runtimes.lua.build(reset=True)                                                        
+ cd /tmp/builders/openssl
+ . /tmp/builders/openssl/env.sh
++ export LIBRARY_PATH=/lib/x86_64-linux-gnu:/lib:/usr/local/lib:/usr/lib
++ LIBRARY_PATH=/lib/x86_64-linux-gnu:/lib:/usr/local/lib:/usr/lib
++ export LD_LIBRARY_PATH=/lib/x86_64-linux-gnu:/lib:/usr/local/lib:/usr/lib
++ LD_LIBRARY_PATH=/lib/x86_64-linux-gnu:/lib:/usr/local/lib:/usr/lib
++ export 'LDFLAGS=-L/lib/x86_64-linux-gnu -L/lib -L/usr/local/lib -L/usr/lib'
++ LDFLAGS='-L/lib/x86_64-linux-gnu -L/lib -L/usr/local/lib -L/usr/lib'
++ export CPPPATH=/usr/include
++ CPPPATH=/usr/include
++ export CPPFLAGS=-I/usr/include
++ CPPFLAGS=-I/usr/include
++ export PS1=PYTHONBUILDENV:
++ PS1=PYTHONBUILDENV:
++ export PYTHONHTTPSVERIFY=0
++ PYTHONHTTPSVERIFY=0
++ export LC_ALL=en_US.UTF-8
++ LC_ALL=en_US.UTF-8
++ export LANG=en_US.UTF-8
++ LANG=en_US.UTF-8
+ cd /tmp/builders/openssl
+ sh ./mycompile_all.sh
+ cd /tmp/builders/openssl
+ git clone --depth 1 https://github.com/openssl/openssl.git
fatal: destination path 'openssl' already exists and is not an empty directory.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/builder/system/BuilderBaseClass.py", line 67, in wrapper_action
    res = func(builder, *args, **kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/builder/runtimes/BuilderLua.py", line 22, in build
    j.builder.libs.openssl.build(reset=reset)
  File "/sandbox/lib/jumpscale/Jumpscale/builder/system/BuilderBaseClass.py", line 67, in wrapper_action
    res = func(builder, *args, **kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/builder/libs/BuilderOpenSSL.py", line 41, in build
    self._execute("cd {DIR_BUILD}; sh ./mycompile_all.sh")
  File "/sandbox/lib/jumpscale/Jumpscale/builder/system/BuilderBaseClass.py", line 277, in _execute
    args=args, interactive=interactive, replace=False, showout=showout)
  File "/sandbox/lib/jumpscale/Jumpscale/sal/process/SystemProcess.py", line 87, in execute
    env=env,interactive=interactive,replace=replace)
  File "/sandbox/lib/jumpscale/Jumpscale/core/InstallTools.py", line 1161, in execute
    raise RuntimeError(msg)
RuntimeError: 
Could not execute:    bash /tmp/builders/openssl/builder_openssl.sh

stderr:
    + cd /tmp/builders/openssl
    + . /tmp/builders/openssl/env.sh
    ++ export LIBRARY_PATH=/lib/x86_64-linux-gnu:/lib:/usr/local/lib:/usr/lib
    ++ LIBRARY_PATH=/lib/x86_64-linux-gnu:/lib:/usr/local/lib:/usr/lib
    ++ export LD_LIBRARY_PATH=/lib/x86_64-linux-gnu:/lib:/usr/local/lib:/usr/lib
    ++ LD_LIBRARY_PATH=/lib/x86_64-linux-gnu:/lib:/usr/local/lib:/usr/lib
    ++ export 'LDFLAGS=-L/lib/x86_64-linux-gnu -L/lib -L/usr/local/lib -L/usr/lib'
    ++ LDFLAGS='-L/lib/x86_64-linux-gnu -L/lib -L/usr/local/lib -L/usr/lib'
    ++ export CPPPATH=/usr/include
    ++ CPPPATH=/usr/include
    ++ export CPPFLAGS=-I/usr/include
    ++ CPPFLAGS=-I/usr/include
    ++ export PS1=PYTHONBUILDENV:
    ++ PS1=PYTHONBUILDENV:
    ++ export PYTHONHTTPSVERIFY=0
    ++ PYTHONHTTPSVERIFY=0
    ++ export LC_ALL=en_US.UTF-8
    ++ LC_ALL=en_US.UTF-8
    ++ export LANG=en_US.UTF-8
    ++ LANG=en_US.UTF-8
    + cd /tmp/builders/openssl
    + sh ./mycompile_all.sh
    + cd /tmp/builders/openssl
    + git clone --depth 1 https://github.com/openssl/openssl.git
    fatal: destination path 'openssl' already exists and is not an empty directory.


Could not execute:    bash /tmp/builders/openssl/builder_openssl.sh

stderr:
    + cd /tmp/builders/openssl
    + . /tmp/builders/openssl/env.sh
    ++ export LIBRARY_PATH=/lib/x86_64-linux-gnu:/lib:/usr/local/lib:/usr/lib
    ++ LIBRARY_PATH=/lib/x86_64-linux-gnu:/lib:/usr/local/lib:/usr/lib
    ++ export LD_LIBRARY_PATH=/lib/x86_64-linux-gnu:/lib:/usr/local/lib:/usr/lib
    ++ LD_LIBRARY_PATH=/lib/x86_64-linux-gnu:/lib:/usr/local/lib:/usr/lib
    ++ export 'LDFLAGS=-L/lib/x86_64-linux-gnu -L/lib -L/usr/local/lib -L/usr/lib'
    ++ LDFLAGS='-L/lib/x86_64-linux-gnu -L/lib -L/usr/local/lib -L/usr/lib'
    ++ export CPPPATH=/usr/include
    ++ CPPPATH=/usr/include
    ++ export CPPFLAGS=-I/usr/include
    ++ CPPFLAGS=-I/usr/include
    ++ export PS1=PYTHONBUILDENV:
    ++ PS1=PYTHONBUILDENV:
    ++ export PYTHONHTTPSVERIFY=0
    ++ PYTHONHTTPSVERIFY=0
    ++ export LC_ALL=en_US.UTF-8
    ++ LC_ALL=en_US.UTF-8
    ++ export LANG=en_US.UTF-8
    ++ LANG=en_US.UTF-8
    + cd /tmp/builders/openssl
    + sh ./mycompile_all.sh
    + cd /tmp/builders/openssl
    + git clone --depth 1 https://github.com/openssl/openssl.git
    fatal: destination path 'openssl' already exists and is not an empty directory.

```

**Comment by DylanVerstraete** [comment]
Same error with `pythonbuilder`, if you have built it before and try to build it again, the builder tries to clone `openssl` in `/tmp/builders/openssl`. 

Temporary fix is:

`rm -rf /tmp/builders/openssl`
and restart kosmos

**Comment by 0xIslamTaha** [comment]
@DylanVerstraete shouldn't `reset=True` delete all olds files?

**Comment by waleedhammam** [comment]
#### Change-log: https://github.com/threefoldtech/jumpscaleX/commit/6fda12b954fb6ee9a086ff4147cf02fe9aa793c0
- Remove `reset` parameters from builder methods as it blocks the decorator handling it according to new implementation technique in docs.

**Comment by AhmedHanafy725** [comment]
**Verified** on 6fda12b954fb6ee9a086ff4147cf02fe9aa793c0
