### ISSUE TITLE
Logging fails when the message contains empty braces

### ISSUE THREAD

**Issue by abom** [threefoldtecharchive/jumpscaleX_archived#465]
It consider empty braces as a positional field for `format()`

To reproduce, make sure the log level is at e.g. 10 (see `/sandbox/cfg/jumpscale_config.toml`).

```
JSX> j.core.tools.log('logging emppty dict {}', level=10)                                                                                                                                                          
```

Will produce:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/core/InstallTools.py", line 417, in log
    Tools.log2stdout(logdict,data_show=data_show)
  File "/sandbox/lib/jumpscale/Jumpscale/core/InstallTools.py", line 874, in log2stdout
    msg=Tools.text_replace(msg,args=logdict)
  File "/sandbox/lib/jumpscale/Jumpscale/core/InstallTools.py", line 802, in text_replace
    content = content.format_map(replace_args)
ValueError: Format string contains positional fields

Format string contains positional fields
```

Also when using gedis:
```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/root/.local/lib/python3.6/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/sandbox/lib/jumpscale/DigitalMe/servers/gedis/handlers.py", line 212, in handle_redis
    self._handle_redis_session(gedis_socket, address)
  File "/sandbox/lib/jumpscale/DigitalMe/servers/gedis/handlers.py", line 232, in _handle_redis_session
    result = self._handle_request(request, address)
  File "/sandbox/lib/jumpscale/DigitalMe/servers/gedis/handlers.py", line 289, in _handle_request
    self._log_debug("params cmd %s %s" % (params_list, params_dict))
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py", line 319, in _log_debug
    self._log(msg,cat=cat,level=10,data=data,context=context,_levelup=_levelup)
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py", line 405, in _log
    j.core.tools.log2stdout(logdict)
  File "/sandbox/lib/jumpscale/Jumpscale/core/InstallTools.py", line 874, in log2stdout
    msg=Tools.text_replace(msg,args=logdict)
  File "/sandbox/lib/jumpscale/Jumpscale/core/InstallTools.py", line 802, in text_replace
    content = content.format_map(replace_args)
ValueError: Format string contains positional fields

```

**Comment by despiegk** [comment]
fixed
