### ISSUE TITLE
installing jsx from development and master branch fails

### ISSUE THREAD

**Issue by zgorizzo69** [threefoldtecharchive/jumpscaleX_archived#475]
OS: Ubuntu 18.04.2 LTS
SHELL: zsh
I followed the install [documentation](https://github.com/threefoldtech/jumpscaleX/blob/development/docs/Installation/install.md)  doing 
```bash 
rm -rf /sandbox;rm -rf /tmp/install.py;rm -rf /tmp/InstallTools.py
sudo mkdir -p /sandbox/code/github/threefoldtech
sudo  chown -R $USER:$USER /sandbox
cd /sandbox/code/github/threefoldtech
git clone git@github.com:threefoldtech/jumpscaleX.git
cd jumpscaleX
git checkout development
git pull
rm -f /tmp/install.py
rm -f /tmp/InstallTools.py
ln -s /sandbox/code/github/threefoldtech/jumpscaleX/install/install.py /tmp/install.py
ln -s /sandbox/code/github/threefoldtech/jumpscaleX/install/InstallTools.py /tmp/InstallTools.py
python3 /tmp/install.py -3 -codepath=/sandbox/code
```
here is the output
```
Reading package lists... Done
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
Traceback (most recent call last):
  File "/tmp/install.py", line 20, in <module>
    IT.MyEnv._init()
  File "/tmp/InstallTools.py", line 2014, in _init
    Tools.execute(script,interactive=True)
  File "/tmp/InstallTools.py", line 1007, in execute
    timeout=timeout,die=die,env=env,self=self,interactive=interactive,asfile=False,original_command=command )
  File "/tmp/InstallTools.py", line 1013, in execute
    res = Tools._execute_interactive(cmd=command, die=die,original_command=original_command)
  File "/tmp/InstallTools.py", line 482, in _execute_interactive
    raise RuntimeError("***ERROR EXECUTE INTERACTIVE:\nCould not execute:%s\nreturncode:%s\n"%(original_command,returncode))
RuntimeError: ***ERROR EXECUTE INTERACTIVE:
Could not execute:if ! grep -Fq "deb http://mirror.unix-solutions.be/ubuntu/ bionic" /etc/apt/sources.list; then
    echo >> /etc/apt/sources.list
    echo "# Jumpscale Setup" >> /etc/apt/sources.list
    echo deb http://mirror.unix-solutions.be/ubuntu/ bionic main universe multiverse restricted >> /etc/apt/sources.list
fi
apt-get update

apt-get install -y curl rsync unzip
locale-gen --purge en_US.UTF-8

mkdir -p /tmp/jumpscale/scripts
mkdir -p /sandbox/var/log

returncode:100
```
if I git checkout master, remove and recreate the symlink, remove /sandbox/cfg and I answer this 
```
Do you want to redo the full install? (means redo pip's ...)

make your choice (y,n): y
Optional: provide secret to use for passphrase, if ok to use SSH-Agent just press 'ENTER'

please provide 24 words of the private key, or just press 'ENTER' for autogeneration.


Jumpscale X Installer
---------------------

 - jumpscale will be installed using docker.
 - location of code path is: /sandbox/code
 - name of container is: default
 - will map ssh port to: '9122'
 - will map portrange '8010-8014:8000-8004' (8000-8004) always in container.


Ok to continue?
make your choice (y,n): y


EXCEPTION

        /tmp/install.py                                              : 329 : j.shell()

Tue 14 15:19:05 install.py       -   1 - <module>                           : EXCEPTION: name 'j' is not defined
CANNOT CONTINUE
```

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/57703405-4b133a00-7660-11e9-8505-132004da584c.png)

clearly this has never been tested
its a debug j.shell() inside?

**Comment by despiegk** [comment]
will fix tomorrow

**Comment by rkhamis** [comment]
@Dina-Abd-Elrahman can you check the master installer?

**Comment by Dina-Abd-Elrahman** [comment]
- i tested the installation from master_hotfix branch and it's working fine for in docker and in system installation.
