### ISSUE TITLE
Builders: PostgreSQL builder

### ISSUE THREAD

**Issue by andrewayoub** [threefoldtecharchive/jumpscaleX_archived#527]
- doesn't follow builders guidlines
- not complete

**Comment by abom** [comment]
Required by #492.

**Comment by abom** [comment]
I'm facing an error where builder profile got removed

```
j.builder.db.postgres.build(reset=True)
```

Then i got:

```
+ cd /tmp/builders/psql
+ . /tmp/builders/psql/env.sh
/tmp/builders/psql/builder_postgresql.sh: line 3: /tmp/builders/psql/env.sh: No such file or directory
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/builder/system/BuilderBaseClass.py", line 108, in wrapper_action
    res = self.apply_method(func, kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/builder/system/BuilderBaseClass.py", line 63, in apply_method
    return func(**kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/builder/db/BuilderPostgresql.py", line 28, in build
    self._execute(cmd)
  File "/sandbox/lib/jumpscale/Jumpscale/builder/system/BuilderBaseClass.py", line 323, in _execute
    showout=showout,
  File "/sandbox/lib/jumpscale/Jumpscale/sal/process/SystemProcess.py", line 103, in execute
    replace=replace,
  File "/sandbox/lib/jumpscale/Jumpscale/core/InstallTools.py", line 1175, in execute
    raise RuntimeError(msg)
RuntimeError: 
Could not execute:    bash /tmp/builders/psql/builder_postgresql.sh

stderr:
    + cd /tmp/builders/psql
    + . /tmp/builders/psql/env.sh
    /tmp/builders/psql/builder_postgresql.sh: line 3: /tmp/builders/psql/env.sh: No such file or directory


Could not execute:    bash /tmp/builders/psql/builder_postgresql.sh

stderr:
    + cd /tmp/builders/psql
    + . /tmp/builders/psql/env.sh
    /tmp/builders/psql/builder_postgresql.sh: line 3: /tmp/builders/psql/env.sh: No such file or directory
```

Trying to investigate what's the problem.

**Comment by abom** [comment]
The cause of the error mentioned [above](https://github.com/threefoldtech/jumpscaleX/issues/527#issuecomment-494414146) is that `j.builder.tool.file_download` will remove the entire destination if `expand=True`

**Comment by abom** [comment]
Fixed, the build is working now (using version 9.6.13).
Will check install() then we should have a working setup.

**Comment by abom** [comment]
Branch: development_builder (#511).

build/install/start/stop should be working now.

**Comment by AhmedHanafy725** [comment]
`j.builder.db.postgres.build()` **in fresh installation.**
```
stderr:
    + cd /sandbox
    + . /sandbox/env.sh
    ++ export LC_ALL=en_US.UTF-8
    ++ LC_ALL=en_US.UTF-8
    ++ export LUALIB=/sandbox/openresty/lualib
    ++ LUALIB=/sandbox/openresty/lualib
    ++ export LANG=en_US.UTF-8
    ++ LANG=en_US.UTF-8
    ++ export 'LUA_PATH=?.lua;/sandbox/openresty/lualib/?/init.lua;/sandbox/openresty/lualib/?.lua;/sandbox/openresty/lualib/?/?.lua;/sandbox/openresty/lualib/?/core.lua;/sandbox/openr
        esty/lapis/?.lua'
    ++ LUA_PATH='?.lua;/sandbox/openresty/lualib/?/init.lua;/sandbox/openresty/lualib/?.lua;/sandbox/openresty/lualib/?/?.lua;/sandbox/openresty/lualib/?/core.lua;/sandbox/openresty/la
        pis/?.lua'
    ++ export PBASE=/sandbox
    ++ PBASE=/sandbox
    ++ export 'LUA_CPATH=/sandbox/openresty/lualib/?.so;./?.so'
    ++ LUA_CPATH='/sandbox/openresty/lualib/?.so;./?.so'
    ++ export PYTHONHTTPSVERIFY=0
    ++ PYTHONHTTPSVERIFY=0
    ++ export HOME=/root
    ++ HOME=/root
    ++ export HOST=faf7e1be4628
    ++ HOST=faf7e1be4628
    ++ export PYTHONPATH=/sandbox/lib:/sandbox/lib/jumpscale:/sandbox/lib:/sandbox/lib/jumpscale:
    ++ PYTHONPATH=/sandbox/lib:/sandbox/lib/jumpscale:/sandbox/lib:/sandbox/lib/jumpscale:
    ++ export PATH=/sandbox/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
    ++ PATH=/sandbox/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
    ++ export 'PS1=3BOTDEVEL:faf7e1be4628:\W: '
    ++ PS1='3BOTDEVEL:faf7e1be4628:\W: '
    ++ export LAPIS_OPENRESTY=/sandbox/bin/openresty
    ++ LAPIS_OPENRESTY=/sandbox/bin/openresty
    + cd /tmp/builders/psql
    + ./configure --prefix=/sandbox/apps/pgsql --bindir=/sandbox/bin --sysconfdir=/sandbox/cfg --libdir=/postgres --datarootdir=/sandbox/apps/pgsql/share
    configure: WARNING:
    *** Without Bison you will not be able to build PostgreSQL from Git nor
    *** change any of the parser definition files.  You can obtain Bison from
    *** a GNU mirror site.  (If you are using the official distribution of
    *** PostgreSQL then you do not need to worry about this, because the Bison
    *** output is pre-generated.)
    configure: WARNING:
    *** Without Flex you will not be able to build PostgreSQL from Git nor
    *** change any of the scanner definition files.  You can obtain Flex from
    *** a GNU mirror site.  (If you are using the official distribution of
    *** PostgreSQL then you do not need to worry about this because the Flex
    *** output is pre-generated.)
    + make
    copy_fetch.c:161:1: error: conflicting types for ‘copy_file_range’
     copy_file_range(const char *path, off_t begin, off_t end, bool trunc)
     ^~~~~~~~~~~~~~~
    In file included from copy_fetch.c:16:0:
    /usr/include/unistd.h:1110:9: note: previous declaration of ‘copy_file_range’ was here
     ssize_t copy_file_range (int __infd, __off64_t *__pinoff,
             ^~~~~~~~~~~~~~~
    make[3]: *** [copy_fetch.o] Error 1
    make[2]: *** [all-pg_rewind-recurse] Error 2
    make[1]: *** [all-bin-recurse] Error 2
    make: *** [all-src-recurse] Error 2
```

`j.builder.db.postgres.install()`
```
Could not execute: 'bash /sandbox/builder_postgresql.sh'stderr:
    + cd /sandbox
    + . /sandbox/env.sh
    ++ export LC_ALL=en_US.UTF-8
    ++ LC_ALL=en_US.UTF-8
    ++ export LUALIB=/sandbox/openresty/lualib
    ++ LUALIB=/sandbox/openresty/lualib
    ++ export LANG=en_US.UTF-8
    ++ LANG=en_US.UTF-8
    ++ export 'LUA_PATH=?.lua;/sandbox/openresty/lualib/?/init.lua;/sandbox/openresty/lualib/?.lua;/sandbox/openresty/lualib/?/?.lua;/sandbox/openresty/lualib/?/core.lua;/sandbox/openr
        esty/lapis/?.lua'
    ++ LUA_PATH='?.lua;/sandbox/openresty/lualib/?/init.lua;/sandbox/openresty/lualib/?.lua;/sandbox/openresty/lualib/?/?.lua;/sandbox/openresty/lualib/?/core.lua;/sandbox/openresty/la
        pis/?.lua'
    ++ export PBASE=/sandbox
    ++ PBASE=/sandbox
    ++ export 'LUA_CPATH=/sandbox/openresty/lualib/?.so;./?.so'
    ++ LUA_CPATH='/sandbox/openresty/lualib/?.so;./?.so'
    ++ export GOPATH=/sandbox/go_proj
    ++ GOPATH=/sandbox/go_proj
    ++ export PYTHONHTTPSVERIFY=0
    ++ PYTHONHTTPSVERIFY=0
    ++ export HOME=/root
    ++ HOME=/root
    ++ export GOROOT=/sandbox/go
    ++ GOROOT=/sandbox/go
    ++ export HOST=57e8e0ac844f
    ++ HOST=57e8e0ac844f
    ++ export PYTHONPATH=/sandbox/lib:/sandbox/lib/jumpscale:/sandbox/lib:/sandbox/lib/jumpscale:
    ++ PYTHONPATH=/sandbox/lib:/sandbox/lib/jumpscale:/sandbox/lib:/sandbox/lib/jumpscale:
    ++ export PATH=/sandbox/go/bin:/sandbox/go_proj/bin:/sandbox/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
    ++ PATH=/sandbox/go/bin:/sandbox/go_proj/bin:/sandbox/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
    ++ export 'PS1=3BOTDEVEL:57e8e0ac844f:\W: '
    ++ PS1='3BOTDEVEL:57e8e0ac844f:\W: '
    ++ export LAPIS_OPENRESTY=/sandbox/bin/openresty
    ++ LAPIS_OPENRESTY=/sandbox/bin/openresty
    + cd /sandbox
    + mkdir -p log
    + mkdir -p /sandbox/apps/psql/data
    + chown -R postgres /sandbox/apps/psql/data
    + sudo -u postgres /sandbox/bin/initdb -D /sandbox/apps/psql/data -E utf8 --locale=en_US.UTF-8
    /sandbox/builder_postgresql.sh: line 8: sudo: command not found
```
**After install sudo**
```
JSX> j.sal.process.getProcessPid('postgres')                                       
[]

JSX> j.builder.db.postgres.start()                                                 
Sun 26 11:03:23 StartupCMD.py    - 121 - startupcmd:startupcmd              : IS RUNNING postgres
JSX> j.builder.db.postgres.stop()                                                  
Sun 26 11:03:28 StartupCMD.py    -  63 - startupcmd:startupcmd              : stop:
postgres
Sun 26 11:03:28 StartupCMD.py    -  70 - startupcmd:startupcmd              : found process to stop:28602
Sun 26 11:03:29 StartupCMD.py    - 102 - startupcmd:startupcmd              : IS HALTED postgres
JSX> j.sal.process.getProcessPid('postgres')                                       
[28603, 28605, 28606, 28607, 28608, 28609]
```
**It didn't stop**
**Builder doesn't have sandbox or test.**

**Comment by abom** [comment]
@AhmedHanafy725 i cannot see what file this builder is downloading, can you give me the output of `ls /tmp/builders/psql`?

Are you sure this test was on a fresh installation? because that compilation error should only appear if you've an old source directory (before 9.6.13).

Also, i updated this builder because we only need it for #492, sandbox() would take more time.

**Comment by AhmedHanafy725** [comment]
@abom for the fresh installation it didn't have your commit fix this and it works fine now.

**Comment by abom** [comment]
@AhmedHanafy725 

> It didn't stop

If startup cmds cannot handle this, should i implement my own stop commands or it would be an issue in startup cmds?

**Comment by andrewayoub** [comment]
> If startup cmds cannot handle this, should i implement my own stop commands or it would be an issue in startup cmds?

yes, If you need special stop you can override stop method in your builder

**Comment by abom** [comment]
Fixed start/stop by using `pg_ctl`, also added `sandbox()`.

**Comment by abom** [comment]
Tried to create an flist with auto-start,  but seems like some libraries are missing, maybe something is still wrong with `j.sandboxer.libs_sandbox()`.


Flist: https://hub.grid.tf/abdelrahman/psql.flist.md

```python
from 
from zeroos.core0.client import Client

cl = Client('node_ip_goes_here')
cont_cl = cl.container.client(container_id_goes_here)
cont_cl.system('/sandbox/bin/pg_ctl start -D /sandbox/apps/psql/data',env={'LD_LIBRARY_PATH':'/sandbox/lib:/lib'}).get()
```

Output:
```

STATE: 0 ERROR
STDOUT:

STDERR:

DATA:
fork/exec /sandbox/bin/pg_ctl: no such file or directory


```

**Comment by abom** [comment]
Will try to set some env variables like `PATH` to see if it's the reason (to resolve https://github.com/threefoldtech/jumpscaleX/issues/527#issuecomment-497368647).

**Update:** Still didn't resolve the issue.

**Comment by abom** [comment]
I'm trying to validate `j.tools.sandboxer`, by creating an flist from a working builder (digitalmex builder).

Will compare the output of the flist with [a working one](https://hub.grid.tf/sboctor/digitalme.flist.md) to see `libs_sandbox()` still working.

**Comment by abom** [comment]
While building digitalmex, capnp builder is broken, tests fail

[test-suite.log](https://github.com/threefoldtech/jumpscaleX/files/3244721/test-suite.log)

**Comment by abom** [comment]
Sandbox now working after fixing j.sandboxer, now i'm trying to make the flist autostart work.

**Comment by abom** [comment]
Finally, seems like the problem was zero-os parsing toml!

zero-os uses https://github.com/naoina/toml to decode toml, which fails if a multi-line string has a double quote inside any line, like the following

https://github.com/threefoldtech/jumpscaleX/blob/ea5e7530beae00e8bab63322186ca670eee55fb9/Jumpscale/builder/db/templates/postgres_startup.toml#L5-L14

Opened an issue at [0-core](https://github.com/threefoldtech/0-core), for now, i [removed these double quotes](https://github.com/threefoldtech/jumpscaleX/commit/c96eb6750c52991d036465b9f162898e5158c789).

**Comment by abom** [comment]
Working flist with auto-start (based on ubuntu)

https://hub.grid.tf/abdelrahman/psql9.6-ubuntu18.04.flist.md

**Comment by AhmedHanafy725** [comment]
Waiting for #603 to be solved

**Comment by AhmedHanafy725** [comment]
**Verified on** 
**branch:** development_builder
**commit:** e2cd62f83b2aba6f565cccdd445e3de3bb6a72d5
Now (`build`, `install`, `start`, `stop`, `test` and `sandbox`) are working fine.
