### ISSUE TITLE
error with capacity reservation with tfchain client 

### ISSUE THREAD

**Issue by Pishoy** [threefoldtecharchive/jumpscaleX_archived#578]
could not find schema error when trying to reserve a zos vm using tf chain client as below 
```
JSX> w.balance                                                                                                                                
wallet balance on height 288547 at 2019/06/02 08:41:51
1200 TFT available and 0 TFT locked

JSX> result = w.threebot.record_new(months=1,names=["my3bottest2.example"],addresses=["example.org"],key_index=0)                             
JSX> result.transaction                                                                                                                       
transaction v144 76619e5879bd5128deacba74e978eeee014089fa75e145d8f102b20ab5adc7c3

JSX> result.submitted                                                                                                                         
True

JSX> result = w.capacity.reserve_zos_vm(email='abdelmab@codescalers.com',threebot_id='my3bottest2.example',location='002522f78706',size=1)    
Sun 02 08:48:09 BCDB.py          - 328 - bcdb:bcdb                          : load model:jumpscale.threefold_directory.client
Sun 02 08:48:13 BCDB.py          - 328 - bcdb:bcdb                          : load model:jumpscale.gedis.client
Sun 02 08:48:13 GedisClient.py   - 138 - j.clients.gedis:gedisclient        : redisclient: notary.grid.tf:5000 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/clients/blockchain/tfchain/TFChainCapacity.py", line 125, in reserve_zos_vm
    return self._process_reservation(reservation, threebot_id, source=source, refund=refund)
  File "/sandbox/lib/jumpscale/Jumpscale/clients/blockchain/tfchain/TFChainCapacity.py", line 225, in _process_reservation
    response = self._notary_client.register(threebot_id, signature.message, signature.signature)
  File "/sandbox/lib/jumpscale/Jumpscale/clients/blockchain/tfchain/TFChainCapacity.py", line 27, in _notary_client
    self._notary_client_ = c.actors.notary_actor
  File "/sandbox/lib/jumpscale/DigitalMe/clients/gedis/GedisClient.py", line 84, in actors
    self._actorsmeta[actor_name] = j.servers.gedis._cmds_get(key, data)
  File "/sandbox/lib/jumpscale/DigitalMe/servers/gedis/GedisFactory.py", line 41, in _cmds_get
    return GedisCmds(namespace=namespace, name=name, data=data)
  File "/sandbox/lib/jumpscale/DigitalMe/servers/gedis/GedisCmds.py", line 50, in __init__
    self.data = self.schema.get(data=data)
  File "/sandbox/lib/jumpscale/Jumpscale/data/schema/Schema.py", line 300, in get
    return j.data.serializers.jsxdata.loads(data)
  File "/sandbox/lib/jumpscale/Jumpscale/data/serializers/SerializerJSXDataObj.py", line 36, in loads
    raise RuntimeError("could not find schema with md5:%s" % md5)
RuntimeError: could not find schema with md5:7f4004110d42110d6a11111611cd267f

```
- jx version 
```
root@d6acd5153fab:/sandbox/code/github/threefoldtech/jumpscaleX# git branch   
  development
* development_tfchain_client

root@d6acd5153fab:/sandbox/code/github/threefoldtech/jumpscaleX# git log -1
commit 6363f103e6a88352616ac614bf39ac9cec8f376f (HEAD -> development_tfchain_client, origin/development_tfchain_client)
Author: Christophe de Carvalho <christophe.dcpm@gmail.com>
Date:   Tue May 28 12:42:59 2019 +0200

    change explorer node schema field to list of string
```

**Comment by zaibon** [comment]
fixed in https://github.com/threefoldtech/jumpscaleX/pull/562
