### ISSUE TITLE
Buidlers: TCPRouter builder

### ISSUE THREAD

**Issue by andrewayoub** [threefoldtecharchive/jumpscaleX_archived#621]
Create builder for [TCPRouter](https://github.com/xmonader/tcprouter)

**Comment by AhmedHanafy725** [comment]
(`build`, `install`, `start`, `stop`) works fine, but `sandbox` raises this error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/builder/system/BuilderBaseClass.py", line 162, in wrapper_action
    res = self.apply_method(func, kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/builder/system/BuilderBaseClass.py", line 93, in apply_method
    return func(**kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/builder/network/BuilderTCPRouter.py", line 53, in sandbox
    self.tools.copyTree(j.builders.db.redis.DIR_SANDBOX, self.DIR_SANDBOX)
  File "/sandbox/lib/jumpscale/Jumpscale/builder/tools/BuilderTools.py", line 115, in copyTree
    createdir=createdir,
  File "/sandbox/lib/jumpscale/Jumpscale/sal/fs/SystemFS.py", line 264, in copyDirTree
    if j.sal.fs.isDir(src):
  File "/sandbox/lib/jumpscale/Jumpscale/sal/fs/SystemFSDecorators.py", line 154, in wrapper
    raise ValueError(msg)
ValueError: Argument path in j.sal.fs.isDir expects an existing path value! /tmp/package/redis-server does not exist.
```

**Comment by siddiquagig** [comment]
Tried this on a fresh install , getting this error :

![tcp](https://user-images.githubusercontent.com/25789724/61857550-72467d00-aed5-11e9-8378-1030b34af2fd.JPG)

Branch : ```development_jumpscale```
```
commit 5020e020db6093500de2f0b8aedd2859f5c43dfe (HEAD -> development_jumpscale, origin/development_jumpscale)
Author: Waleed Hammam <waleed.hammam@gmail.com>
Date:   Thu Jul 25 10:27:59 2019 +0200

    fix code location in installer
```

**Comment by siddiquagig** [comment]
Install, Build, Start and Stop are working now, but sandbox still has a different error now :


```JSX> j.builders.network.tcprouter.sandbox()```
```

Thu 25 12:24:03 Sandboxer.py     - 222 - sandboxer                          : lib sandbox:/sandbox/bin/lapis
Thu 25 12:24:03 Sandboxer.py     - 184 - sandboxer                          : find deb:/sandbox/bin/lapis
        not a dynamic executable
Thu 25 12:24:03 Sandboxer.py     - 222 - sandboxer                          : lib sandbox:/sandbox/bin/moon
Thu 25 12:24:03 Sandboxer.py     - 184 - sandboxer                          : find deb:/sandbox/bin/moon
        not a dynamic executable
Thu 25 12:24:03 Sandboxer.py     - 222 - sandboxer                          : lib sandbox:/sandbox/bin/moonc
Thu 25 12:24:03 Sandboxer.py     - 184 - sandboxer                          : find deb:/sandbox/bin/moonc
        not a dynamic executable
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/builders/system/BuilderBaseClass.py", line 168, in wrapper_action
    res = self.apply_method(func, kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/builders/system/BuilderBaseClass.py", line 93, in apply_method
    return func(**kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/builders/network/BuilderTCPRouter.py", line 54, in sandbox
    j.builders.db.redis.sandbox()
  File "/sandbox/lib/jumpscale/Jumpscale/builders/system/BuilderBaseClass.py", line 168, in wrapper_action
    res = self.apply_method(func, kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/builders/system/BuilderBaseClass.py", line 93, in apply_method
    return func(**kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/builders/db/BuilderRedis.py", line 74, in sandbox
    j.builders.web.openresty.sandbox(reset=reset)
  File "/sandbox/lib/jumpscale/Jumpscale/builders/system/BuilderBaseClass.py", line 168, in wrapper_action
    res = self.apply_method(func, kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/builders/system/BuilderBaseClass.py", line 93, in apply_method
    return func(**kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/builders/web/BuilderOpenResty.py", line 120, in sandbox
    self.tools.copyTree(dir_src, dir_dest)
  File "/sandbox/lib/jumpscale/Jumpscale/builders/tools/BuilderTools.py", line 115, in copyTree
    createdir=createdir,
  File "/sandbox/lib/jumpscale/Jumpscale/sal/fs/SystemFS.py", line 265, in copyDirTree
    if ":" not in src and j.sal.fs.isDir(src):
  File "/sandbox/lib/jumpscale/Jumpscale/sal/fs/SystemFSDecorators.py", line 154, in wrapper
    raise ValueError(msg)
ValueError: Argument path in j.sal.fs.isDir expects an existing path value! /sandbox/cfg/openresty.cfg does not exist.

Argument path in j.sal.fs.isDir expects an existing path value! /sandbox/cfg/openresty.cfg does not exist.

```

```
3BOTDEVEL:3bot:jumpscaleX: git log -1
commit de84017b2cfdfe0479c336a298cd386d79ee883a (HEAD -> development_jumpscale, origin/development_jumpscale)
Author: Waleed Hammam <waleed.hammam@gmail.com>
Date:   Sun Jul 28 13:33:51 2019 +0200

    add error message if no sshkey found

```

**Comment by siddiquagig** [comment]
Verified 
```JSX> j.builders.network.tcprouter.sandbox()```

![tcp router sandbox](https://user-images.githubusercontent.com/25789724/62106477-59afdb80-b2b6-11e9-8383-c57fdc974035.JPG)


```
3BOTDEVEL:3bot:jumpscaleX: git log -1
commit bb4a8275d3b9e0a58b3d99abfe5851e4efba91d5 (HEAD -> development_jumpscale, origin/development_jumpscale)
Author: BolaNasr <bola.nasr@live.com>
Date:   Mon Jul 29 18:35:42 2019 +0200

    fix odoo server
```
