### ISSUE TITLE
Fix BCDB and get tests to run [development_bcdb_refactor]

### ISSUE THREAD

**Issue by andrewayoub** [threefoldtecharchive/jumpscaleX_archived#629]
Fix BCDB and get tests to run
`j.data.bcdb.test()`

**Comment by andrewayoub** [comment]
most of the tests are passing now
the missing tests are
7_redis
10_export
11_redis_index_lost

**Comment by BolaNasr** [comment]
all tests passed now except  ```7_redis ```

**Comment by zgorizzo69** [comment]
> all tests passed now except `7_redis `

when I run test 'export' I have that error.

```Wed 19 14:43:20 BCDB.py          - 481 - bcdb:bcdb                          : generate schema:threefoldtoken.wallet.test2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBFactory.py", line 307, in test
    self._test_run(name=name)
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py", line 477, in _test_run
    res = self.__test_run(name=name, obj_key=obj_key, die=die, **kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py", line 513, in __test_run
    self.__test_run(name=bname, obj_key=obj_key, **kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py", line 534, in __test_run
    res = method(self=self, **kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/tests/10_export.py", line 81, in main
    export_import(encr=False, export=True, remove=True)
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/tests/10_export.py", line 67, in export_import
    obj2 = m3.get(3)
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBDecorator.py", line 41, in wrapper_queue_method
    res = func(*args, **kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBModel.py", line 401, in get
    raise RuntimeError("could not find obj with id:%s" % obj_id)
RuntimeError: could not find obj with id:3

could not find obj with id:3
```

**Comment by zgorizzo69** [comment]
Not relevant anymore
