### ISSUE TITLE
BCDBModel object has no attribute 'get_all' on fresh 3bot container

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/jumpscaleX_archived#634]
Following installation docs
https://github.com/threefoldtech/jumpscaleX/blob/development/docs/Installation/get_started.md

```
JSX> j.clients.gedis                                                                                                      
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/ptpython/repl.py", line 84, in _process_text
    self._execute(line)
  File "/root/.local/lib/python3.6/site-packages/ptpython/repl.py", line 133, in _execute
    result_str = '%r\n' % (result, )
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py", line 567, in __str__
    out = add("children", "GREEN", self._properties_children(), out)
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBaseConfigs.py", line 202, in _properties_children
    for item in self.findData():
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBaseConfigs.py", line 173, in findData
    return self._model.get_all()
AttributeError: 'BCDBModel' object has no attribute 'get_all'



JSX> j.clients.etcd                                                                                                         

Thu 20 07:33:11 BCDB.py          - 465 - bcdb:bcdb                          : load model:jumpscale.etcd.client
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/ptpython/repl.py", line 84, in _process_text
    self._execute(line)
  File "/root/.local/lib/python3.6/site-packages/ptpython/repl.py", line 133, in _execute
    result_str = '%r\n' % (result, )
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py", line 567, in __str__
    out = add("children", "GREEN", self._properties_children(), out)
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBaseConfigs.py", line 202, in _properties_children
    for item in self.findData():
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBaseConfigs.py", line 173, in findData
    return self._model.get_all()
AttributeError: 'BCDBModel' object has no attribute 'get_all'

'BCDBModel' object has no attribute 'get_all'
JSX>                                                                                                                        

```

same for mongodb and others.

**Comment by rkhamis** [comment]
has been changed to `find`, indeed

**Comment by despiegk** [comment]
no longer relevant on #682
