### ISSUE TITLE
jumpscale/DigitalMe/servers/myjobs

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#646]
- get myjobs to work 
- have a return path for results of a function
- move tests to test directory
- check performance
- make documentation

**Comment by abom** [comment]
**Branches**:
_JumpscaleX_: `jumpscale_development`
_DigitalmeX_: `jumpscale_jumpscale_myjobs`


Now after some fixes related to timeout, the following tests run successfully:

* `kosmos -p "j.servers.myjobs.test('basic')"`
* `kosmos -p "j.servers.myjobs.test('simple_error')"`
* `kosmos -p "j.servers.myjobs.test1()"`
* `kosmos -p "j.servers.myjobs.test4()"`

All of them use `worker_start()`, `workers_start()` and sometimes in tmux with `worker_start_tmux()`.

The following tests fail with **_segmentation fault_** (with gevent monkey patching) and block without monkey patching. All of this failed tests uses `start()` method not `worker_start()` directly like successful tests.

* `kosmos -p 'j.servers.myjobs.test2()'`
```
executing method with *args () and **kwargs {} 
Tue 20 13:13:32 BCDBModelIndex.py    - 259 - bcdbindex_myjobs                   : get key(exists):key__5499dc9685789b23391dc51df8d057da
Tue 20 13:13:32 BCDBModelIndex.py    - 259 - bcdbindex_myjobs                   : get key(exists):state__NEW
Tue 20 13:13:32 BCDBModelIndex.py    - 217 - bcdbindex_myjobs                   : set key:state__NEW (id:1672)
Tue 20 13:13:32 BCDBModelIndex.py    - 259 - bcdbindex_myjobs                   : get key(exists):action_id__1586
Tue 20 13:13:32 BCDBModelIndex.py    - 217 - bcdbindex_myjobs                   : set key:action_id__1586 (id:1672)
executing method with *args () and **kwargs {} 
Tue 20 13:13:32 BCDBModelIndex.py    - 259 - bcdbindex_myjobs                   : get key(exists):key__5499dc9685789b23391dc51df8d057da
Tue 20 13:13:32 BCDBModelIndex.py    - 259 - bcdbindex_myjobs                   : get key(exists):state__NEW
Tue 20 13:13:32 BCDBModelIndex.py    - 217 - bcdbindex_myjobs                   : set key:state__NEW (id:1673)
Tue 20 13:13:32 BCDBModelIndex.py    - 259 - bcdbindex_myjobs                   : get key(exists):action_id__1586
Tue 20 13:13:32 BCDBModelIndex.py    - 217 - bcdbindex_myjobs                   : set key:action_id__1586 (id:1673)
executing method with *args () and **kwargs {} 
Tue 20 13:13:32 BCDBModelIndex.py    - 259 - bcdbindex_myjobs                   : get key(exists):key__5499dc9685789b23391dc51df8d057da
Tue 20 13:13:32 BCDBModelIndex.py    - 259 - bcdbindex_myjobs                   : get key(exists):state__NEW
Tue 20 13:13:32 BCDBModelIndex.py    - 217 - bcdbindex_myjobs                   : set key:state__NEW (id:1674)
Tue 20 13:13:32 BCDBModelIndex.py    - 259 - bcdbindex_myjobs                   : get key(exists):action_id__1586
Tue 20 13:13:32 BCDBModelIndex.py    - 217 - bcdbindex_myjobs                   : set key:action_id__1586 (id:1674)
executing method with *args () and **kwargs {} 
Tue 20 13:13:32 BCDBModelIndex.py    - 259 - bcdbindex_myjobs                   : get key(exists):key__5499dc9685789b23391dc51df8d057da
Tue 20 13:13:32 BCDBModelIndex.py    - 259 - bcdbindex_myjobs                   : get key(exists):state__NEW
Tue 20 13:13:32 BCDBModelIndex.py    - 217 - bcdbindex_myjobs                   : set key:state__NEW (id:1675)
Tue 20 13:13:32 BCDBModelIndex.py    - 259 - bcdbindex_myjobs                   : get key(exists):action_id__1586
Tue 20 13:13:32 BCDBModelIndex.py    - 217 - bcdbindex_myjobs                   : set key:action_id__1586 (id:1675)
executing method with *args () and **kwargs {} 
Tue 20 13:13:32 BCDBModelIndex.py    - 259 - bcdbindex_myjobs                   : get key(exists):key__5499dc9685789b23391dc51df8d057da
Tue 20 13:13:32 BCDBModelIndex.py    - 259 - bcdbindex_myjobs                   : get key(exists):state__NEW
Tue 20 13:13:32 BCDBModelIndex.py    - 217 - bcdbindex_myjobs                   : set key:state__NEW (id:1676)
Tue 20 13:13:32 BCDBModelIndex.py    - 259 - bcdbindex_myjobs                   : get key(exists):action_id__1586
Tue 20 13:13:32 BCDBModelIndex.py    - 217 - bcdbindex_myjobs                   : set key:action_id__1586 (id:1676)
Tue 20 13:13:33 MyJobs.py            - 253 - myjobs                             : monitor run
Segmentation fault (core dumped)
```
   Also, workers are still running in background (and prints logs after kosmos exit with seg fault).

   **Trying** without `-p` just will print logs (it actually blocks because of the call of `gevent.joinall()`)




* `kosmos -p 'j.servers.myjobs.test3()'`

Segmentation fault.
```
Tue 20 13:20:59 BCDBModelIndex.py    - 217 - bcdbindex_myjobs                   : set key:state__OK (id:1905)
--DATA-----------------------
  action_id: 1539
  args: []
  category: ''
  error: {}
  id: 2278
  kwargs: {}
  result: OK
  return_queues: []
  state: 3
  time_start: 1566307258
  time_stop: 1566307259
  timeout: 0
-----------------------------

Tue 20 13:20:59 MyWorker.py          - 102 - myworker                           : OK
--DATA-----------------------
  action_id: 1539
  args: []
  category: ''
  error: {}
  id: 2279
  kwargs: {}
  result: ''
  return_queues: []
  state: 1
  time_start: 1566307258
  time_stop: 0
  timeout: 0
-----------------------------

Tue 20 13:20:59 MyWorker.py          - 102 - myworker                           : execute
Segmentation fault (core dumped)
```


   **Trying** without `-p`

Need to be fixed (maybe increase results timeout) as it gives this error
```
Tue 20 13:17:26 MyWorker.py          - 102 - myworker                           : execute
--TRACEBACK------------------
/sandbox/bin/kosmos in <module>
    175    exec(toexec, globals(), j._locals_get({}))
<string> in <module>
    1    
/sandbox/lib/jumpscale/DigitalMe/servers/myjobs/MyJobs.py in test3
    810    res = self.results(ids)
/sandbox/lib/jumpscale/DigitalMe/servers/myjobs/MyJobs.py in results
    529    raise j.exceptions.Base("timeout for results with jobids:%s" % ids)
-----------------------------
Tue 20 13:17:26 ers/myjobs/MyJobs.py - 529 - results                            : EXCEPTION: 
    timeout for results with jobids:[1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1739, 1740,
        1741, 1742, 1743, 1744, 1745, 1746, 1747, 1748, 1749, 1750, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759,
        1760, 1761, 1762, 1763, 1764, 1765, 1766, 1767, 1768, 1769, 1770, 1771, 1772, 1773, 1774, 1775, 1776, 1777, 1778,
        1779, 1780, 1781, 1782, 1783, 1784, 1785, 1786, 1787, 1788, 1789, 1790, 1791, 1792, 1793, 1794, 1795, 1796, 1797,
        1798, 1799, 1800, 1801, 1802, 1803, 1804, 1805, 1806, 1807, 1808, 1809, 1810, 1811, 1812, 1813, 1814, 1815, 1816,
        1817, 1818, 1819, 1820, 1821, 1822, 1823, 1824, 1825, 1826]
Error in sys.excepthook:
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/pudb/debugger.py", line 2147, in call_with_ui
    return f(*args, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/pudb/debugger.py", line 2399, in interaction
    self.event_loop()
  File "/root/.local/lib/python3.6/site-packages/pudb/debugger.py", line 2359, in event_loop
    keys = self.screen.get_input()
  File "/root/.local/lib/python3.6/site-packages/urwid/raw_display.py", line 335, in get_input
    self._wait_for_input_ready(self._next_timeout)
  File "/root/.local/lib/python3.6/site-packages/urwid/raw_display.py", line 535, in _wait_for_input_ready
    fd_list, [], fd_list)
KeyboardInterrupt

Original exception was:
Traceback (most recent call last):
  File "/sandbox/bin/kosmos", line 175, in <module>
    exec(toexec, globals(), j._locals_get({}))
  File "<string>", line 1, in <module>
  File "/sandbox/lib/jumpscale/DigitalMe/servers/myjobs/MyJobs.py", line 810, in test3
    res = self.results(ids)
  File "/sandbox/lib/jumpscale/DigitalMe/servers/myjobs/MyJobs.py", line 529, in results
    raise j.exceptions.Base("timeout for results with jobids:%s" % ids)
Jumpscale.core.InstallTools.BaseJSException: {RED}EXCEPTION: 
    timeout for results with jobids:[1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1739, 1740,
        1741, 1742, 1743, 1744, 1745, 1746, 1747, 1748, 1749, 1750, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759,
        1760, 1761, 1762, 1763, 1764, 1765, 1766, 1767, 1768, 1769, 1770, 1771, 1772, 1773, 1774, 1775, 1776, 1777, 1778,
        1779, 1780, 1781, 1782, 1783, 1784, 1785, 1786, 1787, 1788, 1789, 1790, 1791, 1792, 1793, 1794, 1795, 1796, 1797,
        1798, 1799, 1800, 1801, 1802, 1803, 1804, 1805, 1806, 1807, 1808, 1809, 1810, 1811, 1812, 1813, 1814, 1815, 1816,
        1817, 1818, 1819, 1820, 1821, 1822, 1823, 1824, 1825, 1826]{RESET}
```

**Comment by abom** [comment]
It seems like `start()` still has some problems, maybe it doesn't spawn enough workers or when running the worker in a different process it works, but not in the same process.

**Comment by abom** [comment]
Also, there's some confusion here about the ways of how starting myjobs server, we need to know what's the difference between start() and workers_start() in myjobs (some tests use the first one and others use the later).

What's the standard way of starting this server? so we follow it when doing the tests, also when using it.
