### ISSUE TITLE
Caddy builder doesn't work 

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtecharchive/jumpscaleX_archived#654]
j..builders.web.caddy.build(reset=True) 

##  Issue 
```
+ go mod init caddy
go mod init: go.mod already exists
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/builder/system/BuilderBaseClass.py", line 166, in wrapper_action
    res = self.apply_method(func, kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/builder/system/BuilderBaseClass.py", line 93, in apply_method
    return func(**kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/builder/web/BuilderCaddy.py", line 129, in build
    self._execute("cd {DIR_BUILD} && gofmt caddy.go && go mod init caddy && go install")
  File "/sandbox/lib/jumpscale/Jumpscale/builder/system/BuilderBaseClass.py", line 379, in _execute
    showout=showout,
  File "/sandbox/lib/jumpscale/Jumpscale/sal/process/SystemProcess.py", line 103, in execute
    replace=replace,
  File "/sandbox/lib/jumpscale/Jumpscale/core/InstallTools.py", line 1408, in execute
    raise RuntimeError(msg)
RuntimeError: 
Could not execute:    bash /tmp/builders/caddy/builder_caddy.sh

stdout:
    package main
    
    import (
            "github.com/mholt/caddy/caddy/caddymain"
    
            // plug in plugins here, for example:
            _ "github.com/filebrowser/caddy"
            _ "github.com/itsyouonline/caddy-integration/oauth"
    )
    
    func main() {
            // optional: disable telemetry
            // caddymain.EnableTelemetry = false
            caddymain.Run()
    }

stderr:
    + cd /tmp/builders/caddy
    + . /tmp/builders/caddy/env.sh
    ++ export GOROOT=/sandbox/go
    ++ GOROOT=/sandbox/go
    ++ export GOPATH=/sandbox/go_proj
    ++ GOPATH=/sandbox/go_proj
    ++ export PATH=/sandbox/go/bin:/sandbox/go_proj/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
    ++ PATH=/sandbox/go/bin:/sandbox/go_proj/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
    ++ export GO111MODULE=on
    ++ GO111MODULE=on
    ++ export LIBRARY_PATH=/lib/x86_64-linux-gnu:/lib:/usr/local/lib:/usr/lib
    ++ LIBRARY_PATH=/lib/x86_64-linux-gnu:/lib:/usr/local/lib:/usr/lib
    ++ export LD_LIBRARY_PATH=/lib/x86_64-linux-gnu:/lib:/usr/local/lib:/usr/lib
    ++ LD_LIBRARY_PATH=/lib/x86_64-linux-gnu:/lib:/usr/local/lib:/usr/lib
    ++ export 'LDFLAGS=-L/lib/x86_64-linux-gnu -L/lib -L/usr/local/lib -L/usr/lib'
    ++ LDFLAGS='-L/lib/x86_64-linux-gnu -L/lib -L/usr/local/lib -L/usr/lib'
    ++ export CPPPATH=/usr/include
    ++ CPPPATH=/usr/include
    ++ export CPPFLAGS=-I/usr/include
    ++ CPPFLAGS=-I/usr/include
    ++ export PS1=PYTHONBUILDENV:
    ++ PS1=PYTHONBUILDENV:
    ++ export PYTHONHTTPSVERIFY=0
    ++ PYTHONHTTPSVERIFY=0
    ++ export LC_ALL=en_US.UTF-8
    ++ LC_ALL=en_US.UTF-8
    ++ export LANG=en_US.UTF-8
    ++ LANG=en_US.UTF-8
    + cd /tmp/builders/caddy
    + gofmt caddy.go
    + go mod init caddy
    go mod init: go.mod already exists
```
## Branch
development builder

**Comment by despiegk** [comment]
do on #682

**Comment by ranatrk** [comment]
There is a current issue that Caddy import path changed and so the paths need to be updated in the each plugin used. Currently working on fixing the import path of iyo.

**reference to the change (version 1.0.1) :** https://github.com/caddyserver/caddy/releases

**Comment by ranatrk** [comment]
There are currently 3 issues with Caddy Builder:
1. path in itsyouonline
2. path in filemanager
3. `go mod init` triggers an error ` go mod init: go.mod already exists` when run again when building twice in a row.

**Comment by ranatrk** [comment]
Fix in jumpscaleX : https://github.com/threefoldtech/jumpscaleX/commit/3e6b6b838616b6e530494963d86fa5a4f1c6b05c
- update path used from `mholt/caddy` to `caddyserver/caddy`
- clean now removes the DIR_BUILD therefore if build is to be done multiple times after each other, clean should be used before rebuilding to have a clean environment without **go.mod** file

**Comment by ranatrk** [comment]
A new tag/release needs to be created in https://github.com/itsyouonline/caddy-integration/pull/37 so the changes are shown when` go get` is used.

**Comment by ranatrk** [comment]
- Build working with latest release of caddy-integration: https://github.com/itsyouonline/caddy-integration/releases/tag/v0.9.13

- https://github.com/threefoldtech/jumpscaleX/commit/416891f7dbd5612a82dfafbe78c34f2ffd6e8730

**Comment by Dinaamagdy** [comment]
solved in development_builders
