### ISSUE TITLE
minio builder fail

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtecharchive/jumpscaleX_archived#657]
j.builders.storage.minio()
## Issue 
fails with the following error 
```
=====================================================================
ERROR: test005_minio (test_cases.TestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builder_tracking2/jumpscaleX/Jumpscale/builder/test/builder/test_cases.py", line 74, in test005_minio
    j.builders.storage.minio.build(reset=True)
  File "/sandbox/lib/jumpscale/Jumpscale/builder/system/BuilderBaseClass.py", line 166, in wrapper_action
    res = self.apply_method(func, kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/builder/system/BuilderBaseClass.py", line 93, in apply_method
    return func(**kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/builder/storage/BuilderMinio.py", line 27, in build
    self.get("github.com/minio/minio")
  File "/sandbox/lib/jumpscale/Jumpscale/builder/runtimes/BuilderGolang.py", line 99, in get
    self._execute("go get %s %s" % (flags, url), timeout=10000, die=die)
  File "/sandbox/lib/jumpscale/Jumpscale/builder/system/BuilderBaseClass.py", line 379, in _execute
    showout=showout,
  File "/sandbox/lib/jumpscale/Jumpscale/sal/process/SystemProcess.py", line 103, in execute
    replace=replace,
  File "/sandbox/lib/jumpscale/Jumpscale/core/InstallTools.py", line 1408, in execute
    raise RuntimeError(msg)
RuntimeError: 
Could not execute:    bash /tmp/builders/minio/builder_minio.sh
```

**Comment by despiegk** [comment]
do on #682

**Comment by waleedhammam** [comment]
Branch: **development_builders**
this error is likely a network timeout error yet I encountered another error cause of a dependancy lack, fixed  on: https://github.com/threefoldtech/jumpscaleX/commit/ae636575aac3f894406f37ba1d143556549c56f4

**Comment by Dina-Abd-Elrahman** [comment]
#### Branch : `development_builders`, Commit ID : 4a4e87444c0f5a68a7907fff2eaa16cc57e12ba1

- I tested start, stop, build, install, test, sandbox
