### ISSUE TITLE
start and sandbox methods in  openresty builder don't work 

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtecharchive/jumpscaleX_archived#661]
# steps
- j.builders.web.openresty.build() then install then start 
## Issue
j.builders,web.start() gives the follwoing error

![image](https://user-images.githubusercontent.com/24386802/60403569-3ef72380-9b9f-11e9-8d22-fd3682a1a22f.png)

and in sandbox
```
JSX> j.builders.web.openresty.sandbox(reset=True,zhub_client=zhub_client, flist_create=True,merge_base_flist="tf-autobuilder/threefoldtech-jumpscaleX-development.flist")                                   
JSX>  

```
```
make[2]: Leaving directory '/tmp/builders/openresty/openresty/build/nginx-1.13.6'
make[1]: Leaving directory '/tmp/builders/openresty/openresty/build/nginx-1.13.6'
mkdir -p /sandbox/openresty/site/lualib /sandbox/openresty/site/pod /sandbox/openresty/site/manifest
ln -sf /sandbox/bin/openresty /sandbox/openresty/bin/openresty
+ rm -rf /tmp/builders/openresty
+ rm -f /sandbox/bin/lua
+ ln -s /sandbox/openresty/luajit/bin/luajit /sandbox/bin/lua
Sun 30 23:49:33 uilderBaseClass.py - 318 - builderopenresty:builderopenresty  : sandbox profile path in:/sandbox/env.sh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/builder/system/BuilderBaseClass.py", line 166, in wrapper_action
    res = self.apply_method(func, kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/builder/system/BuilderBaseClass.py", line 93, in apply_method
    return func(**kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/builder/web/BuilderOpenResty.py", line 127, in sandbox
    self._copy(dir_src, dir_dest)
  File "/sandbox/lib/jumpscale/Jumpscale/builder/system/BuilderBaseClass.py", line 416, in _copy
    createdir=True,
  File "/sandbox/lib/jumpscale/Jumpscale/builder/tools/BuilderTools.py", line 115, in copyTree
    createdir=createdir,
  File "/sandbox/lib/jumpscale/Jumpscale/sal/fs/SystemFS.py", line 265, in copyDirTree
    if ":" not in src and j.sal.fs.isDir(src):
  File "/sandbox/lib/jumpscale/Jumpscale/sal/fs/SystemFSDecorators.py", line 154, in wrapper
    raise ValueError(msg)
ValueError: Argument path in j.sal.fs.isDir expects an existing path value! /sandbox/bin/resty does not exist.

Argument path in j.sal.fs.isDir expects an existing path value! /sandbox/bin/resty does not exist.
```

**Comment by despiegk** [comment]
start is working
![image](https://user-images.githubusercontent.com/6021844/60788551-48fbc200-a15d-11e9-8301-6ceb36dc3f89.png)
imrpved
