### ISSUE TITLE
hub builder: start and flist methods doesn't work

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtecharchive/jumpscaleX_archived#669]
## Steps 
j.builders.apps.hub.start()
## Issue
```
Tue 02 12:52:42 StartupCMD.py    - 121 - startupcmd:startupcmd              : IS RUNNING 0-db
Tue 02 12:52:42 StartupCMD.py    - 153 - startupcmd:startupcmd              : no need to start was already started:0-db
## startupcmd Instance: 'zerohub' 

- cmd_start                     : cd /tmp/builders/zerohub/code/hub/python/ && python3 flist-uploader.py
- cmd_stop                      : 
- daemon                        : True
- debug                         : False
- env                           : {}
- interpreter                   : BASH
- name                          : zerohub
- path                          : /tmp
- pid                           : 0
- ports                         : []
- process_strings               : []
- timeout                       : 30



Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/builder/system/BuilderBaseClass.py", line 501, in start
    startupcmd.start()
  File "/sandbox/lib/jumpscale/Jumpscale/tools/startupcmd/StartupCMD.py", line 228, in start
    running = self.wait_running()
  File "/sandbox/lib/jumpscale/Jumpscale/tools/startupcmd/StartupCMD.py", line 134, in wait_running
    self._error_raise("could not start")
  File "/sandbox/lib/jumpscale/Jumpscale/tools/startupcmd/StartupCMD.py", line 40, in _error_raise
    raise RuntimeError(msg)
RuntimeError: error in jsrunprocess:
could not start

error in jsrunprocess:
could not start

```
## Branch 
development_builder

**Comment by Dinaamagdy** [comment]
deployed flist  from  sandbox  doesn't have any directory  for hub or zhub 
```
JSX> cont_client.filesystem.list("/sandbox/bin/")                                                                                                                                                           
[{'name': '_lapis.lua', 'size': 104, 'mode': 493, 'is_dir': False}, {'name': '_moon.lua', 'size': 2872, 'mode': 493, 'is_dir': False}, {'name': '_moonc.lua', 'size': 5732, 'mode': 493, 'is_dir': False}, {'name': '_moonrocks.lua', 'size': 649, 'mode': 493, 'is_dir': False}, {'name': 'env_tmux_detach.sh', 'size': 55, 'mode': 493, 'is_dir': False}, {'name': 'ipdb3', 'size': 220, 'mode': 493, 'is_dir': False}, {'name': 'ipython', 'size': 232, 'mode': 493, 'is_dir': False}, {'name': 'js_alerts', 'size': 60, 'mode': 511, 'is_dir': False}, {'name': 'js_code', 'size': 58, 'mode': 511, 'is_dir': False}, {'name': 'js_init', 'size': 58, 'mode': 511, 'is_dir': False}, {'name': 'js_mux', 'size': 57, 'mode': 511, 'is_dir': False}, {'name': 'js_reset', 'size': 59, 'mode': 511, 'is_dir': False}, {'name': 'js_shell', 'size': 59, 'mode': 511, 'is_dir': False}, {'name': 'js_sync', 'size': 58, 'mode': 511, 'is_dir': False}, {'name': 'json2lua', 'size': 676, 'mode': 493, 'is_dir': False}, {'name': 'kosmos', 'size': 57, 'mode': 511, 'is_dir': False}, {'name': 'lapis', 'size': 350, 'mode': 493, 'is_dir': False}, {'name': 'lua', 'size': 36, 'mode': 511, 'is_dir': False}, {'name': 'luarocks', 'size': 328, 'mode': 493, 'is_dir': False}, {'name': 'moon', 'size': 41, 'mode': 493, 'is_dir': False}, {'name': 'moonc', 'size': 42, 'mode': 493, 'is_dir': False}, {'name': 'notary', 'size': 57, 'mode': 511, 'is_dir': False}, {'name': 'openresty', 'size': 13664648, 'mode': 493, 'is_dir': False}, {'name': 'pudb3', 'size': 215, 'mode': 493, 'is_dir': False}, {'name': 'redis-cli', 'size': 56, 'mode': 493, 'is_dir': False}, {'name': 'resty', 'size': 29476, 'mode': 493, 'is_dir': False}, {'name': 'restydoc', 'size': 14957, 'mode': 493, 'is_dir': False}, {'name': 'restydoc-index', 'size': 8452, 'mode': 493, 'is_dir': False}, {'name': 'zdb', 'size': 276240, 'mode': 493, 'is_dir': False}]
```

**Comment by waleedhammam** [comment]
- For start -> as stated in the builder's docs here: https://github.com/threefoldtech/jumpscaleX/blob/development_builders/Jumpscale/builder/apps/docs/BuilderHub.md
for the first time you have to identify your docker's ip for the hub like here: 
https://github.com/threefoldtech/jumpscaleX/blob/development_builders/Jumpscale/builder/apps/docs/BuilderHub.md#install-locally
then should  start ok.
--
- For sandbox -> the hub's files will be under /sandbox/hub/
also /sandbox/bin/zdb
like the file structure of  this flist: https://hub.grid.tf/hammam/zerohub.flist.md

**Comment by Dina-Abd-Elrahman** [comment]
- verified .
