### ISSUE TITLE
timeout error in build methos in ripple builder 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtecharchive/jumpscaleX_archived#677]
- cannot build ripple builder 

```
-- Using src='https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip'
CMakeFiles/sqlite3.dir/build.make:91: recipe for target '../.nih_c/unix_makefiles/GNU_7.4.0/Release/src/sqlite3-stamp/sqlite3-download' failed
CMakeFiles/Makefile2:321: recipe for target 'CMakeFiles/sqlite3.dir/all' failed
Makefile:129: recipe for target 'all' failed
CMake Error at sqlite3-stamp/download-sqlite3.cmake:159 (message):
  Each download failed!

    error: downloading 'https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         
    


make[2]: *** [../.nih_c/unix_makefiles/GNU_7.4.0/Release/src/sqlite3-stamp/sqlite3-download] Error 1
make[1]: *** [CMakeFiles/sqlite3.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/builder/system/BuilderBaseClass.py", line 162, in wrapper_action
    res = self.apply_method(func, kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/builder/system/BuilderBaseClass.py", line 93, in apply_method
    return func(**kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/builder/blockchain/BuilderRipple.py", line 60, in build
    self._execute(ripple_build_cmd, timeout=4000)
  File "/sandbox/lib/jumpscale/Jumpscale/builder/system/BuilderBaseClass.py", line 375, in _execute
    showout=showout,
  File "/sandbox/lib/jumpscale/Jumpscale/sal/process/SystemProcess.py", line 103, in execute
    replace=replace,
  File "/sandbox/lib/jumpscale/Jumpscale/core/InstallTools.py", line 1175, in execute
    raise RuntimeError(msg)
RuntimeError: 
Could not execute:    bash /tmp/builders/rippled/builder_ripple.sh

stdout:
    Branch 'master' set up to track remote branch 'master' from 'origin'.
    -- The C compiler identification is GNU 7.4.0
    -- The CXX compiler identification is GNU 7.4.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- rippled version: 1.2.4
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
    -- Check if compiler accepts -pthread
    -- Check if compiler accepts -pthread - yes
    -- Found Threads: TRUE
    -- NIH-EP cache path: /tmp/builders/rippled/rippled/.nih_c/unix_makefiles/GNU_7.4.0/Release
    -- BOOST_ROOT: /tmp/builders/rippled/boost_1_67_0
    -- BOOST_LIBRARYDIR:
    -- Boost version: 1.67.0
    -- Found the following Boost libraries:
    --   chrono
    --   context
    --   coroutine
    --   date_time
    --   filesystem
    --   program_options
    --   regex
    --   serialization
    --   system
    --   thread
    --   atomic
    -- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.a (found suitable version "1.1.1", minimum required is "1.0.2")
    -- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
    -- Pausing to download NuDB...
    -- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.a;-pthread (found version "3.0.0")
    -- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
    -- doxygen executable not found -- skipping docs target
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/builders/rippled/rippled/my_build
    Scanning dependencies of target snappy
    [  0%] Creating directories for 'snappy'
    [  1%] Performing download step (git clone) for 'snappy'
    [  2%] No patch step for 'snappy'
    [  3%] Performing update step for 'snappy'
    [  4%] Performing configure step for 'snappy'
    -- snappy configure command succeeded.  See also /tmp/builders/rippled/rippled/.nih_c/unix_makefiles/GNU_7.4.0/Release/src/snappy-stamp/snappy-configure-*.log
    [  5%] Performing build step for 'snappy'
    -- snappy build command succeeded.  See also /tmp/builders/rippled/rippled/.nih_c/unix_makefiles/GNU_7.4.0/Release/src/snappy-stamp/snappy-build-*.log
    [  6%] No install step for 'snappy'
    [  7%] No test step for 'snappy'
    [  8%] Completed 'snappy'
    [  8%] Built target snappy
    Scanning dependencies of target rocksdb
    [  9%] Building CXX object CMakeFiles/rocksdb.dir/src/ripple/unity/rocksdb.cpp.o
    [ 10%] Linking CXX static library librocksdb.a
    [ 10%] Built target rocksdb
    Scanning dependencies of target secp256k1
    [ 11%] Building C object CMakeFiles/secp256k1.dir/src/secp256k1/src/secp256k1.c.o
    [ 12%] Linking C static library libsecp256k1.a
    [ 12%] Built target secp256k1
    Scanning dependencies of target lz4
    [ 13%] Creating directories for 'lz4'
    [ 14%] Performing download step (git clone) for 'lz4'
    [ 15%] No patch step for 'lz4'
    [ 16%] Performing update step for 'lz4'
    [ 16%] Performing configure step for 'lz4'
    -- lz4 configure command succeeded.  See also /tmp/builders/rippled/rippled/.nih_c/unix_makefiles/GNU_7.4.0/Release/src/lz4-stamp/lz4-configure-*.log
    [ 17%] Performing build step for 'lz4'
    -- lz4 build command succeeded.  See also /tmp/builders/rippled/rippled/.nih_c/unix_makefiles/GNU_7.4.0/Release/src/lz4-stamp/lz4-build-*.log
    [ 18%] No install step for 'lz4'
    [ 19%] No test step for 'lz4'
    [ 20%] Completed 'lz4'
    [ 20%] Built target lz4
    Scanning dependencies of target libarchive
    [ 21%] Creating directories for 'libarchive'
    [ 22%] Performing download step (git clone) for 'libarchive'
    [ 23%] No patch step for 'libarchive'
    [ 24%] Performing update step for 'libarchive'
    [ 24%] Performing configure step for 'libarchive'
    -- libarchive configure command succeeded.  See also /tmp/builders/rippled/rippled/.nih_c/unix_makefiles/GNU_7.4.0/Release/src/libarchive-stamp/libarchive-configure-*.log
    [ 25%] Performing build step for 'libarchive'
    -- libarchive build command succeeded.  See also /tmp/builders/rippled/rippled/.nih_c/unix_makefiles/GNU_7.4.0/Release/src/libarchive-stamp/libarchive-build-*.log
    [ 26%] No install step for 'libarchive'
    [ 27%] No test step for 'libarchive'
    [ 28%] Completed 'libarchive'
    [ 28%] Built target libarchive
    Scanning dependencies of target ed25519-donna
    [ 28%] Building C object CMakeFiles/ed25519-donna.dir/src/ed25519-donna/ed25519.c.o
    [ 29%] Linking C static library libed25519-donna.a
    [ 29%] Built target ed25519-donna
    Scanning dependencies of target xrpl_core
    [ 30%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/beast/core/core.unity.cpp.o
    [ 30%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/beast/unity/beast_hash_unity.cpp.o
    [ 31%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/beast/unity/beast_insight_unity.cpp.o
    [ 32%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/beast/unity/beast_net_unity.cpp.o
    [ 33%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/beast/unity/beast_utility_unity.cpp.o
    [ 34%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/unity/basics1.cpp.o
    [ 35%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/unity/json.cpp.o
    [ 36%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/unity/protocol.cpp.o
    [ 37%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/unity/crypto.cpp.o
    [ 38%] Linking CXX static library libxrpl_core.a
    [ 38%] Built target xrpl_core
    [ 39%] Running cpp protocol buffer compiler on src/ripple/proto/ripple.proto
    Scanning dependencies of target pbufs
    [ 40%] Building CXX object CMakeFiles/pbufs.dir/proto_gen/ripple.pb.cc.o
    [ 41%] Linking CXX static library libpbufs.a
    [ 41%] Built target pbufs
    Scanning dependencies of target sqlite3
    [ 42%] Creating directories for 'sqlite3'
    [ 43%] Performing download step (download, verify and extract) for 'sqlite3'
    -- Downloading...
       dst='/tmp/builders/rippled/rippled/.nih_c/unix_makefiles/GNU_7.4.0/Release/src/sqlite-amalgamation-3260000.zip'
       timeout='none'
    -- Using src='https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip'
    -- Retrying...
    -- Using src='https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip'
    -- Retry after 5 seconds (attempt #2) ...
    -- Using src='https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip'
    -- Retry after 5 seconds (attempt #3) ...
    -- Using src='https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip'
    -- Retry after 15 seconds (attempt #4) ...
    -- Using src='https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip'
    -- Retry after 60 seconds (attempt #5) ...
    -- Using src='https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip'
    CMakeFiles/sqlite3.dir/build.make:91: recipe for target '../.nih_c/unix_makefiles/GNU_7.4.0/Release/src/sqlite3-stamp/sqlite3-download' failed
    CMakeFiles/Makefile2:321: recipe for target 'CMakeFiles/sqlite3.dir/all' failed
    Makefile:129: recipe for target 'all' failed

stderr:
    + cd /tmp/builders/rippled
    + . /tmp/builders/rippled/env.sh
    ++ export LIBRARY_PATH=/lib/x86_64-linux-gnu:/lib:/usr/local/lib:/usr/lib
    ++ LIBRARY_PATH=/lib/x86_64-linux-gnu:/lib:/usr/local/lib:/usr/lib
    ++ export LD_LIBRARY_PATH=/lib/x86_64-linux-gnu:/lib:/usr/local/lib:/usr/lib
    ++ LD_LIBRARY_PATH=/lib/x86_64-linux-gnu:/lib:/usr/local/lib:/usr/lib
    ++ export 'LDFLAGS=-L/lib/x86_64-linux-gnu -L/lib -L/usr/local/lib -L/usr/lib'
    ++ LDFLAGS='-L/lib/x86_64-linux-gnu -L/lib -L/usr/local/lib -L/usr/lib'
    ++ export CPPPATH=/usr/include
    ++ CPPPATH=/usr/include
    ++ export CPPFLAGS=-I/usr/include
    ++ CPPFLAGS=-I/usr/include
    ++ export PS1=PYTHONBUILDENV:
    ++ PS1=PYTHONBUILDENV:
    ++ export PYTHONHTTPSVERIFY=0
    ++ PYTHONHTTPSVERIFY=0
    ++ export LC_ALL=en_US.UTF-8
    ++ LC_ALL=en_US.UTF-8
    ++ export LANG=en_US.UTF-8
    ++ LANG=en_US.UTF-8
    + cd /tmp/builders/rippled
    + rm -rf rippled
    + git clone https://github.com/ripple/rippled.git
    Cloning into 'rippled'...
    + cd rippled
    + git checkout master
    Switched to a new branch 'master'
    + mkdir my_build
    + cd my_build
    + export BOOST_ROOT=/tmp/builders/rippled/boost_1_67_0
    + BOOST_ROOT=/tmp/builders/rippled/boost_1_67_0
    + cmake .. -DCMAKE_BUILD_TYPE=Release
    + cmake --build .
    Cloning into 'snappy'...
    Note: checking out '1.1.7'.
    
    You are in 'detached HEAD' state. You can look around, make experimental
    changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by performing another checkout.
    
    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -b with the checkout command again. Example:
    
      git checkout -b <new-branch-name>
    
    HEAD is now at b02bfa7 Tag open source release 1.1.7.
    Cloning into 'lz4'...
    Note: checking out 'v1.8.2'.
    
    You are in 'detached HEAD' state. You can look around, make experimental
    changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by performing another checkout.
    
    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -b with the checkout command again. Example:
    
      git checkout -b <new-branch-name>
    
    HEAD is now at b3692db Merge pull request #531 from lz4/dev
    Cloning into 'libarchive'...
    Note: checking out 'v3.3.3'.
    
    You are in 'detached HEAD' state. You can look around, make experimental
    changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by performing another checkout.
    
    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -b with the checkout command again. Example:
    
      git checkout -b <new-branch-name>
    
    HEAD is now at 5fe69dd0 3.3.3
    CMake Error at sqlite3-stamp/download-sqlite3.cmake:159 (message):
      Each download failed!
    
        error: downloading 'https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip' failed
             status_code: 1
             status_string: "Unsupported protocol"
             log:
             --- LOG BEGIN ---
             Protocol "https" not supported or disabled in libcurl
    
      Closing connection -1
    
    
    
             --- LOG END ---
             error: downloading 'https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip' failed
             status_code: 1
             status_string: "Unsupported protocol"
             log:
             --- LOG BEGIN ---
             Protocol "https" not supported or disabled in libcurl
    
      Closing connection -1
    
    
    
             --- LOG END ---
             error: downloading 'https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip' failed
             status_code: 1
             status_string: "Unsupported protocol"
             log:
             --- LOG BEGIN ---
             Protocol "https" not supported or disabled in libcurl
    
      Closing connection -1
    
    
    
             --- LOG END ---
             error: downloading 'https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip' failed
             status_code: 1
             status_string: "Unsupported protocol"
             log:
             --- LOG BEGIN ---
             Protocol "https" not supported or disabled in libcurl
    
      Closing connection -1
    
    
    
             --- LOG END ---
             error: downloading 'https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip' failed
             status_code: 1
             status_string: "Unsupported protocol"
             log:
             --- LOG BEGIN ---
             Protocol "https" not supported or disabled in libcurl
    
      Closing connection -1
    
    
    
             --- LOG END ---
             error: downloading 'https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip' failed
             status_code: 1
             status_string: "Unsupported protocol"
             log:
             --- LOG BEGIN ---
             Protocol "https" not supported or disabled in libcurl
    
      Closing connection -1
    
    
    
             --- LOG END ---
    
    
    
    
    make[2]: *** [../.nih_c/unix_makefiles/GNU_7.4.0/Release/src/sqlite3-stamp/sqlite3-download] Error 1
    make[1]: *** [CMakeFiles/sqlite3.dir/all] Error 2
    make: *** [all] Error 2


Could not execute:    bash /tmp/builders/rippled/builder_ripple.sh

stdout:
    Branch 'master' set up to track remote branch 'master' from 'origin'.
    -- The C compiler identification is GNU 7.4.0
    -- The CXX compiler identification is GNU 7.4.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- rippled version: 1.2.4
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
    -- Check if compiler accepts -pthread
    -- Check if compiler accepts -pthread - yes
    -- Found Threads: TRUE
    -- NIH-EP cache path: /tmp/builders/rippled/rippled/.nih_c/unix_makefiles/GNU_7.4.0/Release
    -- BOOST_ROOT: /tmp/builders/rippled/boost_1_67_0
    -- BOOST_LIBRARYDIR:
    -- Boost version: 1.67.0
    -- Found the following Boost libraries:
    --   chrono
    --   context
    --   coroutine
    --   date_time
    --   filesystem
    --   program_options
    --   regex
    --   serialization
    --   system
    --   thread
    --   atomic
    -- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.a (found suitable version "1.1.1", minimum required is "1.0.2")
    -- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
    -- Pausing to download NuDB...
    -- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.a;-pthread (found version "3.0.0")
    -- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
    -- doxygen executable not found -- skipping docs target
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/builders/rippled/rippled/my_build
    Scanning dependencies of target snappy
    [  0%] Creating directories for 'snappy'
    [  1%] Performing download step (git clone) for 'snappy'
    [  2%] No patch step for 'snappy'
    [  3%] Performing update step for 'snappy'
    [  4%] Performing configure step for 'snappy'
    -- snappy configure command succeeded.  See also /tmp/builders/rippled/rippled/.nih_c/unix_makefiles/GNU_7.4.0/Release/src/snappy-stamp/snappy-configure-*.log
    [  5%] Performing build step for 'snappy'
    -- snappy build command succeeded.  See also /tmp/builders/rippled/rippled/.nih_c/unix_makefiles/GNU_7.4.0/Release/src/snappy-stamp/snappy-build-*.log
    [  6%] No install step for 'snappy'
    [  7%] No test step for 'snappy'
    [  8%] Completed 'snappy'
    [  8%] Built target snappy
    Scanning dependencies of target rocksdb
    [  9%] Building CXX object CMakeFiles/rocksdb.dir/src/ripple/unity/rocksdb.cpp.o
    [ 10%] Linking CXX static library librocksdb.a
    [ 10%] Built target rocksdb
    Scanning dependencies of target secp256k1
    [ 11%] Building C object CMakeFiles/secp256k1.dir/src/secp256k1/src/secp256k1.c.o
    [ 12%] Linking C static library libsecp256k1.a
    [ 12%] Built target secp256k1
    Scanning dependencies of target lz4
    [ 13%] Creating directories for 'lz4'
    [ 14%] Performing download step (git clone) for 'lz4'
    [ 15%] No patch step for 'lz4'
    [ 16%] Performing update step for 'lz4'
    [ 16%] Performing configure step for 'lz4'
    -- lz4 configure command succeeded.  See also /tmp/builders/rippled/rippled/.nih_c/unix_makefiles/GNU_7.4.0/Release/src/lz4-stamp/lz4-configure-*.log
    [ 17%] Performing build step for 'lz4'
    -- lz4 build command succeeded.  See also /tmp/builders/rippled/rippled/.nih_c/unix_makefiles/GNU_7.4.0/Release/src/lz4-stamp/lz4-build-*.log
    [ 18%] No install step for 'lz4'
    [ 19%] No test step for 'lz4'
    [ 20%] Completed 'lz4'
    [ 20%] Built target lz4
    Scanning dependencies of target libarchive
    [ 21%] Creating directories for 'libarchive'
    [ 22%] Performing download step (git clone) for 'libarchive'
    [ 23%] No patch step for 'libarchive'
    [ 24%] Performing update step for 'libarchive'
    [ 24%] Performing configure step for 'libarchive'
    -- libarchive configure command succeeded.  See also /tmp/builders/rippled/rippled/.nih_c/unix_makefiles/GNU_7.4.0/Release/src/libarchive-stamp/libarchive-configure-*.log
    [ 25%] Performing build step for 'libarchive'
    -- libarchive build command succeeded.  See also /tmp/builders/rippled/rippled/.nih_c/unix_makefiles/GNU_7.4.0/Release/src/libarchive-stamp/libarchive-build-*.log
    [ 26%] No install step for 'libarchive'
    [ 27%] No test step for 'libarchive'
    [ 28%] Completed 'libarchive'
    [ 28%] Built target libarchive
    Scanning dependencies of target ed25519-donna
    [ 28%] Building C object CMakeFiles/ed25519-donna.dir/src/ed25519-donna/ed25519.c.o
    [ 29%] Linking C static library libed25519-donna.a
    [ 29%] Built target ed25519-donna
    Scanning dependencies of target xrpl_core
    [ 30%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/beast/core/core.unity.cpp.o
    [ 30%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/beast/unity/beast_hash_unity.cpp.o
    [ 31%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/beast/unity/beast_insight_unity.cpp.o
    [ 32%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/beast/unity/beast_net_unity.cpp.o
    [ 33%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/beast/unity/beast_utility_unity.cpp.o
    [ 34%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/unity/basics1.cpp.o
    [ 35%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/unity/json.cpp.o
    [ 36%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/unity/protocol.cpp.o
    [ 37%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/unity/crypto.cpp.o
    [ 38%] Linking CXX static library libxrpl_core.a
    [ 38%] Built target xrpl_core
    [ 39%] Running cpp protocol buffer compiler on src/ripple/proto/ripple.proto
    Scanning dependencies of target pbufs
    [ 40%] Building CXX object CMakeFiles/pbufs.dir/proto_gen/ripple.pb.cc.o
    [ 41%] Linking CXX static library libpbufs.a
    [ 41%] Built target pbufs
    Scanning dependencies of target sqlite3
    [ 42%] Creating directories for 'sqlite3'
    [ 43%] Performing download step (download, verify and extract) for 'sqlite3'
    -- Downloading...
       dst='/tmp/builders/rippled/rippled/.nih_c/unix_makefiles/GNU_7.4.0/Release/src/sqlite-amalgamation-3260000.zip'
       timeout='none'
    -- Using src='https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip'
    -- Retrying...
    -- Using src='https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip'
    -- Retry after 5 seconds (attempt #2) ...
    -- Using src='https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip'
    -- Retry after 5 seconds (attempt #3) ...
    -- Using src='https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip'
    -- Retry after 15 seconds (attempt #4) ...
    -- Using src='https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip'
    -- Retry after 60 seconds (attempt #5) ...
    -- Using src='https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip'
    CMakeFiles/sqlite3.dir/build.make:91: recipe for target '../.nih_c/unix_makefiles/GNU_7.4.0/Release/src/sqlite3-stamp/sqlite3-download' failed
    CMakeFiles/Makefile2:321: recipe for target 'CMakeFiles/sqlite3.dir/all' failed
    Makefile:129: recipe for target 'all' failed

stderr:
    + cd /tmp/builders/rippled
    + . /tmp/builders/rippled/env.sh
    ++ export LIBRARY_PATH=/lib/x86_64-linux-gnu:/lib:/usr/local/lib:/usr/lib
    ++ LIBRARY_PATH=/lib/x86_64-linux-gnu:/lib:/usr/local/lib:/usr/lib
    ++ export LD_LIBRARY_PATH=/lib/x86_64-linux-gnu:/lib:/usr/local/lib:/usr/lib
    ++ LD_LIBRARY_PATH=/lib/x86_64-linux-gnu:/lib:/usr/local/lib:/usr/lib
    ++ export 'LDFLAGS=-L/lib/x86_64-linux-gnu -L/lib -L/usr/local/lib -L/usr/lib'
    ++ LDFLAGS='-L/lib/x86_64-linux-gnu -L/lib -L/usr/local/lib -L/usr/lib'
    ++ export CPPPATH=/usr/include
    ++ CPPPATH=/usr/include
    ++ export CPPFLAGS=-I/usr/include
    ++ CPPFLAGS=-I/usr/include
    ++ export PS1=PYTHONBUILDENV:
    ++ PS1=PYTHONBUILDENV:
    ++ export PYTHONHTTPSVERIFY=0
    ++ PYTHONHTTPSVERIFY=0
    ++ export LC_ALL=en_US.UTF-8
    ++ LC_ALL=en_US.UTF-8
    ++ export LANG=en_US.UTF-8
    ++ LANG=en_US.UTF-8
    + cd /tmp/builders/rippled
    + rm -rf rippled
    + git clone https://github.com/ripple/rippled.git
    Cloning into 'rippled'...
    + cd rippled
    + git checkout master
    Switched to a new branch 'master'
    + mkdir my_build
    + cd my_build
    + export BOOST_ROOT=/tmp/builders/rippled/boost_1_67_0
    + BOOST_ROOT=/tmp/builders/rippled/boost_1_67_0
    + cmake .. -DCMAKE_BUILD_TYPE=Release
    + cmake --build .
    Cloning into 'snappy'...
    Note: checking out '1.1.7'.
    
    You are in 'detached HEAD' state. You can look around, make experimental
    changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by performing another checkout.
    
    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -b with the checkout command again. Example:
    
      git checkout -b <new-branch-name>
    
    HEAD is now at b02bfa7 Tag open source release 1.1.7.
    Cloning into 'lz4'...
    Note: checking out 'v1.8.2'.
    
    You are in 'detached HEAD' state. You can look around, make experimental
    changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by performing another checkout.
    
    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -b with the checkout command again. Example:
    
      git checkout -b <new-branch-name>
    
    HEAD is now at b3692db Merge pull request #531 from lz4/dev
    Cloning into 'libarchive'...
    Note: checking out 'v3.3.3'.
    
    You are in 'detached HEAD' state. You can look around, make experimental
    changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by performing another checkout.
    
    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -b with the checkout command again. Example:
    
      git checkout -b <new-branch-name>
    
    HEAD is now at 5fe69dd0 3.3.3
    CMake Error at sqlite3-stamp/download-sqlite3.cmake:159 (message):
      Each download failed!
    
        error: downloading 'https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip' failed
             status_code: 1
             status_string: "Unsupported protocol"
             log:
             --- LOG BEGIN ---
             Protocol "https" not supported or disabled in libcurl
    
      Closing connection -1
    
    
    
             --- LOG END ---
             error: downloading 'https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip' failed
             status_code: 1
             status_string: "Unsupported protocol"
             log:
             --- LOG BEGIN ---
             Protocol "https" not supported or disabled in libcurl
    
      Closing connection -1
    
    
    
             --- LOG END ---
             error: downloading 'https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip' failed
             status_code: 1
             status_string: "Unsupported protocol"
             log:
             --- LOG BEGIN ---
             Protocol "https" not supported or disabled in libcurl
    
      Closing connection -1
    
    
    
             --- LOG END ---
             error: downloading 'https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip' failed
             status_code: 1
             status_string: "Unsupported protocol"
             log:
             --- LOG BEGIN ---
             Protocol "https" not supported or disabled in libcurl
    
      Closing connection -1
    
    
    
             --- LOG END ---
             error: downloading 'https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip' failed
             status_code: 1
             status_string: "Unsupported protocol"
             log:
             --- LOG BEGIN ---
             Protocol "https" not supported or disabled in libcurl
    
      Closing connection -1
    
    
    
             --- LOG END ---
             error: downloading 'https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip' failed
             status_code: 1
             status_string: "Unsupported protocol"
             log:
             --- LOG BEGIN ---
             Protocol "https" not supported or disabled in libcurl
    
      Closing connection -1
    
    
    
             --- LOG END ---
    
    
    
    
    make[2]: *** [../.nih_c/unix_makefiles/GNU_7.4.0/Release/src/sqlite3-stamp/sqlite3-download] Error 1
make[1]: *** [CMakeFiles/sqlite3.dir/all] Error 2
```

**Comment by waleedhammam** [comment]
On branch **development_builders** working ok

**Comment by Dina-Abd-Elrahman** [comment]
- it's working fin now on `development_builders` branch, tested methods: build, install, start, stop, sandbox.

#### Commit ID: `94db33b3c33880839f99cf26406a011423ddc57d`
