### ISSUE TITLE
finish openresty factory

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#709]
- use http(s) client
- do 2 nginx webservers
    - use 1 nginx forward to other nginx static page
   - test using JSX http client
- implement letsencrypt configuration
    - do this by using grack webserver (j.servers.rack) and implement super simple webserver which will answer in right way to letsencrypt
    - test on digitalocean VM

**Comment by andrewayoub** [comment]
Using lua-resty-auto-ssl library made it requires no extra configurations at all, it will issue certificate for any domain.
see example [here](https://testdigitalocean.threefold.io) 

I have also refactored the test to use jumpscale http client instead of requests 

and the test now creates two servers one hosting static page and the other one is the proxy server

**Comment by Pishoy** [comment]
- can not run test method in openrsty as below 
```
JSX> j.builders.web.openresty.install()                                                                                                       
Sun 28 11:15:34 uilderBaseClass.py - 142 - builderopenresty                   : no need to do: builderopenresty:{}, was already done
+ cd /tmp/
+ . /sandbox/env.sh
++ export LC_ALL=en_US.UTF-8
++ LC_ALL=en_US.UTF-8
++ export LUALIB=/sandbox/openresty/lualib
++ LUALIB=/sandbox/openresty/lualib
++ export LANG=en_US.UTF-8
++ LANG=en_US.UTF-8
++ export 'LUA_PATH=?.lua;/sandbox/openresty/lualib/?/init.lua;/sandbox/openresty/lualib/?.lua;/sandbox/openresty/lualib/?/?.lua;/sandbox/openresty/lualib/?/core.lua;/sandbox/openresty/lapis/?.lua'
++ LUA_PATH='?.lua;/sandbox/openresty/lualib/?/init.lua;/sandbox/openresty/lualib/?.lua;/sandbox/openresty/lualib/?/?.lua;/sandbox/openresty/lualib/?/core.lua;/sandbox/openresty/lapis/?.lua'
++ export PBASE=/sandbox
++ PBASE=/sandbox
++ export 'LUA_CPATH=/sandbox/openresty/lualib/?.so;./?.so'
++ LUA_CPATH='/sandbox/openresty/lualib/?.so;./?.so'
++ export PYTHONHTTPSVERIFY=0
++ PYTHONHTTPSVERIFY=0
++ export HOME=/root
++ HOME=/root
++ export HOST=3bot
++ HOST=3bot
++ export PYTHONPATH=/sandbox/lib:/sandbox/lib/jumpscale:/sandbox/lib:/sandbox/lib/jumpscale:
++ PYTHONPATH=/sandbox/lib:/sandbox/lib/jumpscale:/sandbox/lib:/sandbox/lib/jumpscale:
++ export PATH=/sandbox/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
++ PATH=/sandbox/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
++ export 'PS1=3BOTDEVEL:3bot:\W: '
++ PS1='3BOTDEVEL:3bot:\W: '
++ export LAPIS_OPENRESTY=/sandbox/bin/openresty
++ LAPIS_OPENRESTY=/sandbox/bin/openresty
+ ln -s /sandbox/openresty/bin/resty /sandbox/bin/resty
ln: failed to create symbolic link '/sandbox/bin/resty': File exists
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/builders/system/BuilderBaseClass.py", line 168, in wrapper_action
    res = self.apply_method(func, kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/builders/system/BuilderBaseClass.py", line 93, in apply_method
    return func(**kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/builders/web/BuilderOpenResty.py", line 65, in install
    self._execute(C)
  File "/sandbox/lib/jumpscale/Jumpscale/builders/system/BuilderBaseClass.py", line 379, in _execute
    showout=showout,
  File "/sandbox/lib/jumpscale/Jumpscale/sal/process/SystemProcess.py", line 108, in execute
    replace=replace,
  File "/sandbox/lib/jumpscale/Jumpscale/core/InstallTools.py", line 1421, in execute
    raise RuntimeError(msg)
RuntimeError: 
Could not execute: 'bash /tmp/builder_openresty.sh'stderr:
    + cd /tmp/
    + . /sandbox/env.sh
    ++ export LC_ALL=en_US.UTF-8
    ++ LC_ALL=en_US.UTF-8
    ++ export LUALIB=/sandbox/openresty/lualib
    ++ LUALIB=/sandbox/openresty/lualib
    ++ export LANG=en_US.UTF-8
    ++ LANG=en_US.UTF-8
    ++ export 'LUA_PATH=?.lua;/sandbox/openresty/lualib/?/init.lua;/sandbox/openresty/lualib/?.lua;/sandbox/openresty/lualib/?/?.lua;/sandbox/openresty/lualib/?/core.lua;/sandbox/openr
        esty/lapis/?.lua'
    ++ LUA_PATH='?.lua;/sandbox/openresty/lualib/?/init.lua;/sandbox/openresty/lualib/?.lua;/sandbox/openresty/lualib/?/?.lua;/sandbox/openresty/lualib/?/core.lua;/sandbox/openresty/la
        pis/?.lua'
    ++ export PBASE=/sandbox
    ++ PBASE=/sandbox
    ++ export 'LUA_CPATH=/sandbox/openresty/lualib/?.so;./?.so'
    ++ LUA_CPATH='/sandbox/openresty/lualib/?.so;./?.so'
    ++ export PYTHONHTTPSVERIFY=0
    ++ PYTHONHTTPSVERIFY=0
    ++ export HOME=/root
    ++ HOME=/root
    ++ export HOST=3bot
    ++ HOST=3bot
    ++ export PYTHONPATH=/sandbox/lib:/sandbox/lib/jumpscale:/sandbox/lib:/sandbox/lib/jumpscale:
    ++ PYTHONPATH=/sandbox/lib:/sandbox/lib/jumpscale:/sandbox/lib:/sandbox/lib/jumpscale:
    ++ export PATH=/sandbox/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
    ++ PATH=/sandbox/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
    ++ export 'PS1=3BOTDEVEL:3bot:\W: '
    ++ PS1='3BOTDEVEL:3bot:\W: '
    ++ export LAPIS_OPENRESTY=/sandbox/bin/openresty
    ++ LAPIS_OPENRESTY=/sandbox/bin/openresty
    + ln -s /sandbox/openresty/bin/resty /sandbox/bin/resty
    ln: failed to create symbolic link '/sandbox/bin/resty': File exists


Could not execute: 'bash /tmp/builder_openresty.sh'stderr:
    + cd /tmp/
    + . /sandbox/env.sh
    ++ export LC_ALL=en_US.UTF-8
    ++ LC_ALL=en_US.UTF-8
    ++ export LUALIB=/sandbox/openresty/lualib
    ++ LUALIB=/sandbox/openresty/lualib
    ++ export LANG=en_US.UTF-8
    ++ LANG=en_US.UTF-8
    ++ export 'LUA_PATH=?.lua;/sandbox/openresty/lualib/?/init.lua;/sandbox/openresty/lualib/?.lua;/sandbox/openresty/lualib/?/?.lua;/sandbox/openresty/lualib/?/core.lua;/sandbox/openr
        esty/lapis/?.lua'
    ++ LUA_PATH='?.lua;/sandbox/openresty/lualib/?/init.lua;/sandbox/openresty/lualib/?.lua;/sandbox/openresty/lualib/?/?.lua;/sandbox/openresty/lualib/?/core.lua;/sandbox/openresty/la
        pis/?.lua'
    ++ export PBASE=/sandbox
    ++ PBASE=/sandbox
    ++ export 'LUA_CPATH=/sandbox/openresty/lualib/?.so;./?.so'
    ++ LUA_CPATH='/sandbox/openresty/lualib/?.so;./?.so'
    ++ export PYTHONHTTPSVERIFY=0
    ++ PYTHONHTTPSVERIFY=0
    ++ export HOME=/root
    ++ HOME=/root
    ++ export HOST=3bot
    ++ HOST=3bot
    ++ export PYTHONPATH=/sandbox/lib:/sandbox/lib/jumpscale:/sandbox/lib:/sandbox/lib/jumpscale:
    ++ PYTHONPATH=/sandbox/lib:/sandbox/lib/jumpscale:/sandbox/lib:/sandbox/lib/jumpscale:
    ++ export PATH=/sandbox/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
    ++ PATH=/sandbox/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
    ++ export 'PS1=3BOTDEVEL:3bot:\W: '
    ++ PS1='3BOTDEVEL:3bot:\W: '
    ++ export LAPIS_OPENRESTY=/sandbox/bin/openresty
    ++ LAPIS_OPENRESTY=/sandbox/bin/openresty
    + ln -s /sandbox/openresty/bin/resty /sandbox/bin/resty
    ln: failed to create symbolic link '/sandbox/bin/resty': File exists


JSX> j.builders.web.openresty.test()                                                                                                          
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/builders/web/BuilderOpenResty.py", line 232, in test
    if self.running():
  File "/sandbox/lib/jumpscale/Jumpscale/builders/system/BuilderBaseClass.py", line 524, in running
    for startupcmd in self.startup_cmds:
  File "/sandbox/lib/jumpscale/Jumpscale/builders/web/BuilderOpenResty.py", line 212, in startup_cmds
    raise RuntimeError("cannot use lapis here, need openresty allone")
RuntimeError: cannot use lapis here, need openresty allone

cannot use lapis here, need openresty allone

JSX> j.builders.web.lapis.uninstall()           
                                                                                              
JSX> j.builders.web.openresty.uninstall()        
                                                                                             
JSX> j.builders.web.openresty.test()         
                                                                                                 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/builders/web/BuilderOpenResty.py", line 232, in test
    if self.running():
  File "/sandbox/lib/jumpscale/Jumpscale/builders/system/BuilderBaseClass.py", line 524, in running
    for startupcmd in self.startup_cmds:
  File "/sandbox/lib/jumpscale/Jumpscale/builders/web/BuilderOpenResty.py", line 212, in startup_cmds
    raise RuntimeError("cannot use lapis here, need openresty allone")
RuntimeError: cannot use lapis here, need openresty allone

cannot use lapis here, need openresty allone
JSX>  

```

**Comment by BolaNasr** [comment]
```j.builders.web.openresty.install(reset=True)```
![image](https://user-images.githubusercontent.com/10259267/62365207-ce3b8200-b523-11e9-8bf7-c18897f31afe.png)


```j.builders.web.openresty.test()```
![image](https://user-images.githubusercontent.com/10259267/62367511-2ecdbd80-b52a-11e9-9eab-f30bdd731644.png)

**Comment by Pishoy** [comment]
still am getting error with development_jumpscale branch 
steps : 
```
j.builders.web.openresty.install(reset=True)
j.builders.web.openresty.test()
```
- error as attached screenshot
![image](https://user-images.githubusercontent.com/21987477/62685937-f4e63680-b9c3-11e9-9f04-95563ca92bd1.png)

- jsx version 
```
3BOTDEVEL:3bot:jumpscaleX: git log -1
commit 99c3ef8cec4fefca9351db70abb8ff1f3d952f91 (HEAD -> development_jumpscale, origin/development_jumpscale)
Author: Waleed Hammam <waleed.hammam@gmail.com>
Date:   Thu Aug 8 09:56:56 2019 +0200

    fix knownhosts file not found
```
