### ISSUE TITLE
ssh client raises an error

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtecharchive/jumpscaleX_archived#720]
when trying to create/get a ssh client instance it raises:
 `AttributeError: type object 'SSHClientFactory' has no attribute '_SCHEMATEXT'`

 **full stacktrace**
JSX> `j.clients.ssh.new("test_client") `

```
Sun 14 13:30:38 pscale_sshkey_1.py - 192 - jumpscale.sshkey.1                 : change:port22
Sun 14 13:30:38 pscale_sshkey_1.py - 229 - jumpscale.sshkey.1                 : change:loginroot
Sun 14 13:30:38 pscale_sshkey_1.py - 414 - jumpscale.sshkey.1                 : change:stdoutTrue
Sun 14 13:30:38 pscale_sshkey_1.py - 451 - jumpscale.sshkey.1                 : change:forward_agentTrue
Sun 14 13:30:38 pscale_sshkey_1.py - 488 - jumpscale.sshkey.1                 : change:allow_agentTrue
Sun 14 13:30:38 pscale_sshkey_1.py - 525 - jumpscale.sshkey.1                 : change:client_typePARAMIKO
Sun 14 13:30:38 pscale_sshkey_1.py - 562 - jumpscale.sshkey.1                 : change:timeout60
Sun 14 13:30:38 pscale_sshkey_1.py - 118 - jumpscale.sshkey.1                 : change:nametest_client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigs.py", line 74, in new
    return self._new(name=name, jsxobject=jsxobject, **kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigs.py", line 94, in _new
    jsconfig = jsconfig_klass(parent=self, jsxobject=jsxobject)
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py", line 49, in __init__
    self._init_pre(**kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfig.py", line 23, in _init_pre
    s = self._parent.__class__._SCHEMATEXT
AttributeError: type object 'SSHClientFactory' has no attribute '_SCHEMATEXT'

type object 'SSHClientFactory' has no attribute '_SCHEMATEXT'
```

**Comment by waleedhammam** [comment]
fixed at https://github.com/threefoldtech/jumpscaleX/commit/a07c78f30177a249796fad31d1ce9197c0f783ba branch **development_jumpscale**
