### ISSUE TITLE
could not find attribute:wallets in tfchainclient

### ISSUE THREAD

**Issue by 0xIslamTaha** [threefoldtecharchive/jumpscaleX_archived#723]
```
JSX> tft_client = j.clients.tfchain.new(name='tft_client', network_type='TEST')                                                                                                                                    
Tue 16 13:55:20 _tfchain_client.py -  95 - jumpscale.tfchain.client           : change:network_typeSTD
Tue 16 13:55:20 _tfchain_client.py -  95 - jumpscale.tfchain.client           : change:network_typeTEST
Tue 16 13:55:20 _tfchain_client.py -  58 - jumpscale.tfchain.client           : change:nametft_client
JSX> wallet = tft_client.wallets.new('wallet001', seed='slam table target hand drift aim brief fit dizzy flash engine attend oil steel manage oblige mercy duck razor steak crash essay coin stone')               
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/Attr.py", line 43, in __getattr__
    raise RuntimeError(msg)
RuntimeError: could not find attribute:wallets in tfchainclient

could not find attribute:wallets in tfchainclient
JSX> exit()                                                                     
```

**Branch**
jumpscale_development

**Hint**
It is working on `development` branch

**Comment by serboctor** [comment]
Fixed https://github.com/threefoldtech/jumpscaleX/commit/530ae596c8896196cab581099434a97eb40dd3f8

**Comment by siddiquagig** [comment]
Works now:

![devjs](https://user-images.githubusercontent.com/25789724/61434520-406a6f00-a947-11e9-9dc0-d09222d3bf38.JPG)



```
3BOTDEVEL:3bot:jumpscaleX: git log -1
commit dd04c79d5196efdeb6c492ec1464e91a29cae1af (HEAD -> development_jumpscale, origin/development_jumpscale)
Merge: bdb920a5 d67141f0
Author: serboctor <boctor.sarah@gmail.com>
Date:   Wed Jul 17 18:30:57 2019 +0200

    Merge branch 'development_jumpscale' of github.com:threefoldtech/jumpscaleX into development_jumpscale
```
