### ISSUE TITLE
ZOS client :issue with connecting 

### ISSUE THREAD

**Issue by ranatrk** [threefoldtecharchive/jumpscaleX_archived#742]
- ZOS client doesn't connect to the node intended and timeout occurs. A valid jwt is used.
- branch:  **[development_builders]**
- Steps:
   ```
    zos_node = j.clients.zos.get(name="test_zos_node",host=host_ip,password=jwt) 
    zos_node.ping()
     ```
- Error: 
![Screenshot from 2019-07-23 16-43-00](https://user-images.githubusercontent.com/17128393/61721630-0d6e1400-ad69-11e9-854e-d9155893b960.png)

**Comment by AhmedHanafy725** [comment]
**Update**
**branch:** development_jumpscale
**commit:** 7229c13485c925726fb10228bf1ebebc1dd1fc03
Now there is another error when trying to get a client from zos client.
`zos_node = j.clients.zos.get(name="test_zos_node",host=host_ip,password=jwt)`
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigs.py", line 107, in get
    jsconfig = self._new(name=name, **kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigs.py", line 94, in _new
    jsconfig = jsconfig_klass(parent=self, jsxobject=jsxobject)
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py", line 53, in __init__
    self._init(**kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/clients/zero_os/ZeroOSClient.py", line 24, in _init
    port=self.port,
  File "/sandbox/lib/jumpscale/Jumpscale/sal_zos/node/Node.py", line 57, in port
    return self.client.port
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/Attr.py", line 43, in __getattr__
    raise RuntimeError(msg)
RuntimeError: could not find attribute:client in zeroosclient

could not find attribute:client in zeroosclient
```

**Comment by Dinaamagdy** [comment]
have same error like ahmed 
could not find attribute:client in zeroosclient
```                      
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigs.py", line 107, in get
    jsconfig = self._new(name=name, **kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigs.py", line 94, in _new
    jsconfig = jsconfig_klass(parent=self, jsxobject=jsxobject)
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py", line 53, in __init__
    self._init(**kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/clients/zero_os/ZeroOSClient.py", line 24, in _init
    port=self.port,
  File "/sandbox/lib/jumpscale/Jumpscale/sal_zos/node/Node.py", line 57, in port
    return self.client.port
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/Attr.py", line 43, in __getattr__
    raise RuntimeError(msg)
RuntimeError: could not find attribute:client in zeroosclient
```

**Comment by waleedhammam** [comment]
resolved at https://github.com/threefoldtech/jumpscaleX/commit/aac15ad2c53ee669aae35b4c1dfb0b684450ce14

**Comment by Pishoy** [comment]
verified 
![image](https://user-images.githubusercontent.com/21987477/63223671-d3522f80-c1b9-11e9-971f-715c90496199.png)

- js version 
```
3BOTDEVEL:3bot:jumpscaleX: git log -1
commit 4b9836d1a94daf821a7bde816aca9447cc722440 (HEAD -> development_jumpscale, origin/development_jumpscale)
Merge: 4dec1554 403741b2
Author: serboctor <boctor.sarah@gmail.com>
Date:   Sun Aug 18 11:56:51 2019 +0200

    Merge branch 'development_jumpscale' of github.com:threefoldtech/jumpscaleX into development_jumpscale
```
